2024-06-05 11:11:51 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:11:55 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 11:11:55 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 11:15:52 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801e17175861520942895e156d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:15:52 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:15:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 11:15:53 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801e17175861533813092e156d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:15:53 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:15:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 11:15:55 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801e17175861556733437e156d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:15:55 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:15:58 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 11:15:59 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801e17175861589723875e156d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:15:59 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:16:03 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 11:16:03 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 11:18:07 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802617175862871463586e4eb9","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:18:07 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:18:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 11:18:08 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802617175862884393715e4eb9","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:18:08 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:18:10 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 11:18:10 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802617175862907274029e4eb9","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:18:10 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:18:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 11:18:14 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802617175862940374528e4eb9","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:18:14 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:18:18 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 11:18:18 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 11:18:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/10/00/39/39/113276649_p0.jpg
2024-06-05 11:22:07 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802417175865274612238e5b52","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:22:07 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:22:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 11:22:08 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802417175865287492423e5b52","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:22:08 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:22:10 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 11:22:11 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802417175865310402838e5b52","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:22:11 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:22:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 11:22:14 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802417175865343243357e5b52","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:22:14 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:22:18 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 11:22:18 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 11:25:50 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701717175867499261559e6b4f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:25:50 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:25:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 11:25:51 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701717175867512171781e6b4f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:25:51 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:25:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 11:25:53 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701717175867535612133e6b4f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:25:53 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:25:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 11:25:57 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701717175867568542505e6b4f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:25:57 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:26:01 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 11:26:01 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 11:26:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701717175867995538533e6b4f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:26:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:26:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 11:26:41 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701717175868008418668e6b4f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:26:41 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:26:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 11:26:43 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701717175868031328920e6b4f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:26:43 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:26:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 11:26:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701717175868064211384e6b4f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:26:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:26:50 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 11:26:50 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 11:41:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802117175877064641011e6020","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:41:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:41:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 11:41:47 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802117175877077531159e6020","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:41:47 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:41:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 11:41:50 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802117175877100391436e6020","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:41:50 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:41:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 11:41:53 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802117175877133281919e6020","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:41:53 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:41:57 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 11:41:57 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 11:46:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802217175879958383485e4eac","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:46:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:46:37 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 11:46:37 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802217175879971233611e4eac","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:46:37 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:46:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 11:46:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802217175879994073835e4eac","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:46:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:46:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 11:46:42 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802217175880026964228e4eac","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:46:42 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:46:46 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 11:46:46 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 11:48:24 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701317175881042595741e0266","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:48:24 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:48:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 11:48:25 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701317175881055515870e0266","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:48:25 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:48:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 11:48:28 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701317175881078386064e0266","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:48:28 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:48:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 11:48:31 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701317175881111306390e0266","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:48:31 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:48:35 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 11:48:35 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 11:50:17 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/31/00/00/23/115624422_p0.jpg
2024-06-05 11:50:42 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802317175882423397382e54ea","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:50:42 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:50:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 11:50:43 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802317175882436497533e54ea","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:50:43 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:50:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 11:50:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802317175882459437718e54ea","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:50:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:50:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 11:50:49 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802317175882492278016e54ea","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 11:50:49 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 11:50:53 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 11:50:53 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 12:07:27 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803517175892473116525e49ce","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:07:27 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:07:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 12:07:28 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803517175892486246671e49ce","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:07:28 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:07:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 12:07:31 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803517175892509186900e49ce","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:07:31 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:07:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 12:07:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803517175892542067266e49ce","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:07:34 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:07:38 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 12:07:38 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 12:09:13 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/07/22/06/00/13/110125322_p0.jpg
2024-06-05 12:17:18 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-05 12:24:22 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/05/22/00/00/26/118936191_p0.jpg
2024-06-05 12:26:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700f17175903604573520e0264","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:26:00 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:26:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 12:26:01 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700f17175903617403608e0264","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:26:01 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:26:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 12:26:04 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700f17175903640313864e0264","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:26:04 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:26:07 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 12:26:07 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700f17175903673394253e0264","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:26:07 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:26:11 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 12:26:11 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 12:32:22 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800217175907418906187e025b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:32:22 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:32:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 12:32:23 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800217175907431826342e025b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:32:23 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:32:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 12:32:25 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800217175907454666713e025b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:32:25 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:32:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 12:32:28 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800217175907487797246e025b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:32:28 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:32:32 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 12:32:32 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 12:36:55 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /6JjQNYp5%2F889478%2F635fce31343d7343966348139b5e7174fed41259%2F66605bc9294aaf7923c3401aa37be42c66b33448?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5b2Bo2HrO4Z7vW%2FThKHoXIyf%2BZ72JztkTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUj7DwPBqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQzHJ3Sm3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHucqQ%2FXtuMkagAGJG8fqQO1ICt4IeCuCKD0bvyQrTuZCK7%2FeMVkfjhyp885qRcaJa26p1xBnMkT5bvW4twaqUkRnyTf3FNJcQ4IyOhT51QOXtDWXbWMWrxXWOvAPh94aabbk%2FPZn76j9%2Fg65sUuNO%2F4HUYHlFnLBloS7HqDzp3WscheFliHpqeKQyCAA&uploadId=E0DC7467EE8A43588E4EF20E6DE07849&x-oss-access-key-id=STS.NUCM73A18Y7TL46ErgsiW7YFs&x-oss-expires=1717594585&x-oss-signature=eQanmojYzUSJ1e9Pu%2BVB3uh1FmN3P%2BiAb34ZLR0J%2BE4%3D&x-oss-signature-version=OSS2
2024-06-05 12:38:37 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/28/00/00/26/118215398_p0.png
2024-06-05 12:45:33 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701117175915329403590e5f47","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:45:33 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:45:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 12:45:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701117175915342303703e5f47","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:45:34 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:45:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 12:45:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701117175915365294024e5f47","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:45:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:45:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 12:45:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701117175915398114392e5f47","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:45:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:45:43 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 12:45:43 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 12:45:56 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701117175915568026749e5f47","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:45:56 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:45:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 12:45:58 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701117175915580876933e5f47","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:45:58 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:46:00 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 12:46:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701117175915603797255e5f47","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:46:00 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:46:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 12:46:03 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701117175915636947744e5f47","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:46:03 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:46:07 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 12:46:07 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 12:54:29 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701a17175920688768113e2bf8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:54:29 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:54:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 12:54:30 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701a17175920701678270e2bf8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:54:30 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:54:32 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 12:54:32 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701a17175920724598548e2bf8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:54:32 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:54:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 12:54:37 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701417175920772901244e026d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:54:37 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:54:41 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 12:54:41 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 12:55:11 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701417175921117765304e026d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:55:11 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:55:12 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 12:55:13 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701417175921130665519e026d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:55:13 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:55:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 12:55:15 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701417175921153855927e026d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:55:15 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:55:18 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 12:55:18 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701417175921186746463e026d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 12:55:18 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 12:55:22 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 12:55:22 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 13:07:54 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-06-05 13:07:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 13:12:31 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702a17175931509651362e4f3f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 13:12:31 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 13:12:32 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 13:12:32 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702a17175931522561477e4f3f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 13:12:32 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 13:12:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 13:12:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702a17175931545801753e4f3f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 13:12:34 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 13:12:37 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 13:12:38 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702a17175931578652116e4f3f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 13:12:38 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 13:12:42 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 13:12:42 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 13:14:36 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /WSNNghBr%2F889478%2F661fb4de31a5970830d04c099295676d41e71468%2F6660649e70d03b378692444b9c86811af944ed93?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5b2Bo2HrO4Z7vW%2FThKHoXIyf%2BZ72JztkTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUj7DwPBqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQzHJ3Sm3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHucqQ%2FXtuMkagAGJG8fqQO1ICt4IeCuCKD0bvyQrTuZCK7%2FeMVkfjhyp885qRcaJa26p1xBnMkT5bvW4twaqUkRnyTf3FNJcQ4IyOhT51QOXtDWXbWMWrxXWOvAPh94aabbk%2FPZn76j9%2Fg65sUuNO%2F4HUYHlFnLBloS7HqDzp3WscheFliHpqeKQyCAA&uploadId=A0F317E1E88E4361B16FBC125837A4CE&x-oss-access-key-id=STS.NUCM73A18Y7TL46ErgsiW7YFs&x-oss-expires=1717596846&x-oss-signature=k9IShtb1b7wuL3DMY47DioFoDJjluEV5M%2BpBoJVQRFE%3D&x-oss-signature-version=OSS2
2024-06-05 13:14:38 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/WSNNghBr%2F889478%2F661fb4de31a5970830d04c099295676d41e71468%2F6660649e70d03b378692444b9c86811af944ed93?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5b2Bo2HrO4Z7vW%2FThKHoXIyf%2BZ72JztkTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUj7DwPBqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQzHJ3Sm3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHucqQ%2FXtuMkagAGJG8fqQO1ICt4IeCuCKD0bvyQrTuZCK7%2FeMVkfjhyp885qRcaJa26p1xBnMkT5bvW4twaqUkRnyTf3FNJcQ4IyOhT51QOXtDWXbWMWrxXWOvAPh94aabbk%2FPZn76j9%2Fg65sUuNO%2F4HUYHlFnLBloS7HqDzp3WscheFliHpqeKQyCAA&uploadId=A0F317E1E88E4361B16FBC125837A4CE&x-oss-access-key-id=STS.NUCM73A18Y7TL46ErgsiW7YFs&x-oss-expires=1717596846&x-oss-signature=k9IShtb1b7wuL3DMY47DioFoDJjluEV5M%2BpBoJVQRFE%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>666064BD77D65E3333178E0C</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"9549D0EE914F6426BA2743BC1492D328"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-06-05 13:14:38 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/WSNNghBr%2F889478%2F661fb4de31a5970830d04c099295676d41e71468%2F6660649e70d03b378692444b9c86811af944ed93?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5b2Bo2HrO4Z7vW%2FThKHoXIyf%2BZ72JztkTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUj7DwPBqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQzHJ3Sm3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHucqQ%2FXtuMkagAGJG8fqQO1ICt4IeCuCKD0bvyQrTuZCK7%2FeMVkfjhyp885qRcaJa26p1xBnMkT5bvW4twaqUkRnyTf3FNJcQ4IyOhT51QOXtDWXbWMWrxXWOvAPh94aabbk%2FPZn76j9%2Fg65sUuNO%2F4HUYHlFnLBloS7HqDzp3WscheFliHpqeKQyCAA&uploadId=A0F317E1E88E4361B16FBC125837A4CE&x-oss-access-key-id=STS.NUCM73A18Y7TL46ErgsiW7YFs&x-oss-expires=1717596846&x-oss-signature=k9IShtb1b7wuL3DMY47DioFoDJjluEV5M%2BpBoJVQRFE%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>666064BE77D65E3333768E0C</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"9549D0EE914F6426BA2743BC1492D328"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-06-05 13:14:38 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/WSNNghBr%2F889478%2F661fb4de31a5970830d04c099295676d41e71468%2F6660649e70d03b378692444b9c86811af944ed93?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5b2Bo2HrO4Z7vW%2FThKHoXIyf%2BZ72JztkTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUj7DwPBqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQzHJ3Sm3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHucqQ%2FXtuMkagAGJG8fqQO1ICt4IeCuCKD0bvyQrTuZCK7%2FeMVkfjhyp885qRcaJa26p1xBnMkT5bvW4twaqUkRnyTf3FNJcQ4IyOhT51QOXtDWXbWMWrxXWOvAPh94aabbk%2FPZn76j9%2Fg65sUuNO%2F4HUYHlFnLBloS7HqDzp3WscheFliHpqeKQyCAA&uploadId=A0F317E1E88E4361B16FBC125837A4CE&x-oss-access-key-id=STS.NUCM73A18Y7TL46ErgsiW7YFs&x-oss-expires=1717596846&x-oss-signature=k9IShtb1b7wuL3DMY47DioFoDJjluEV5M%2BpBoJVQRFE%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>666064BE77D65E3333B18E0C</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"9549D0EE914F6426BA2743BC1492D328"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-06-05 13:14:38 - ERROR - aliyundrive.py - 1077 - File tmp/117622583/117622583.json.txt Part 1 upload failed.
2024-06-05 13:14:59 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801e17175932992741414e1576","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 13:14:59 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 13:15:00 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 13:15:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801e17175933005661616e1576","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 13:15:00 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 13:15:02 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 13:15:03 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801e17175933028561916e1576","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 13:15:03 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 13:15:06 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 13:15:06 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801e17175933061702368e1576","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 13:15:06 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 13:15:10 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 13:15:10 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 22:16:25 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-05 22:17:29 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702b17176258494025140e4e2e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:17:29 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:17:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 22:17:30 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702b17176258506385273e4e2e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:17:30 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:17:32 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 22:17:33 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702b17176258528755611e4e2e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:17:33 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:17:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 22:17:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702b17176258561295964e4e2e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:17:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:17:40 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 22:17:40 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 22:25:26 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803417176263267973820e5571","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:25:26 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:25:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 22:25:28 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803417176263280533975e5571","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:25:28 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:25:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 22:25:30 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803417176263303104138e5571","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:25:30 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:25:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 22:25:33 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803417176263335664425e5571","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:25:33 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:25:37 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 22:25:37 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 22:28:05 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702b17176264849145134e4e29","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:28:05 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:28:06 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 22:28:06 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702b17176264861745198e4e29","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:28:06 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:28:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 22:28:08 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702b17176264884335341e4e29","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:28:08 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:28:11 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 22:28:11 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702b17176264916905656e4e29","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:28:11 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:28:15 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 22:28:15 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 22:32:01 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/03/12/17/31/15/116854295_p0.png
2024-06-05 22:32:42 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702617176267623228218e4f62","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:32:42 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:32:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 22:32:43 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702617176267635588336e4f62","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:32:43 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:32:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 22:32:45 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702617176267657918524e4f62","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:32:45 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:32:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 22:32:49 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702617176267690268932e4f62","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:32:49 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:32:53 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 22:32:53 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 22:33:04 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702617176267840412294e4f62","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:33:04 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:33:05 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 22:33:05 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702617176267852802385e4f62","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:33:05 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:33:07 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 22:33:07 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702617176267875152545e4f62","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:33:07 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:33:10 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 22:33:10 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702617176267907462822e4f62","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:33:10 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:33:14 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 22:33:14 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 22:37:05 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702517176270258617424e4a8a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:37:05 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:37:06 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 22:37:07 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702517176270270907554e4a8a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:37:07 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:37:09 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 22:37:09 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702517176270293227789e4a8a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:37:09 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:37:12 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 22:37:12 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702517176270325788088e4a8a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:37:12 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:37:16 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 22:37:16 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 22:38:10 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /3gITERGm%2F889478%2F661fc0baa82440a2f4194a3f80b672e5a00a50b3%2F6660e8b4e1952dccb223419a9d4314f099fcb732?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5fvB%2BDlrpITx7G9aVWJolZnXc1n2pefgTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNQDUYXDAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneY%2FAU3RT364IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16ilHI82%2FXtuMkagAEEVIv6w9%2B7gdnvte0tdCnIyhUQwA3Ki3rqGm34ynNdM0fcFjmRHVwBj5ZO7nv%2Fc4bZh25CLLfQMAQRrei3pjdzkwj7y1QOPNx9xb%2FOhZVThYbQnAKFkYD5Tn%2B2hLMFWlU%2F3R6ikrmyzXQpXoatsxmI%2Bx0CVbzdZ5CMPGKraCz5iSAA&uploadId=B5E255B6698A437B878F38E0A66BF7FC&x-oss-access-key-id=STS.NTZLZQCM2psVks8FV2QBK5R4c&x-oss-expires=1717630660&x-oss-signature=bd9B6DOcHes1QIZYyz3861SGJgzxIONkf1%2BLcoAqKic%3D&x-oss-signature-version=OSS2
2024-06-05 22:39:42 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701217176271826314374e5eb4","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:39:42 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:39:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 22:39:44 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701217176271838904508e5eb4","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:39:44 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:39:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 22:39:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701217176271861754689e5eb4","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:39:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:39:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 22:39:49 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701217176271894354972e5eb4","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:39:49 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:39:53 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 22:39:53 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 22:48:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017176277194996967e4f63","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:48:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:48:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 22:48:40 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017176277207577129e4f63","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:48:40 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:48:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 22:48:43 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017176277230157350e4f63","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:48:43 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:48:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 22:48:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017176277262777643e4f63","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:48:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:48:50 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 22:48:50 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 22:49:01 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017176277417798899e4f63","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:49:01 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:49:02 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 22:49:03 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017176277430388994e4f63","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:49:03 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:49:05 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 22:49:05 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017176277452951252e4f63","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:49:05 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:49:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 22:49:08 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802017176277485561526e4f63","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 22:49:08 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 22:49:12 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 22:49:12 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:26:38 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-06-05 23:26:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:26:52 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801d17176300126464582e4e9e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:26:52 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:26:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:26:54 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801d17176300138824734e4e9e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:26:54 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:26:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:26:56 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801d17176300161115043e4e9e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:26:56 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:26:59 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:26:59 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801d17176300193465408e4e9e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:26:59 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:27:03 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:27:03 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:27:17 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801d17176300374017742e4e9e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:27:17 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:27:18 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:27:18 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801d17176300386327819e4e9e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:27:18 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:27:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:27:21 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801d17176300408658064e4e9e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:27:21 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:27:24 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:27:24 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801d17176300440998323e4e9e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:27:24 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:27:28 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:27:28 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:31:22 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701117176302827422485e5f4a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:31:22 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:31:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:31:24 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701117176302839772675e5f4a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:31:24 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:31:26 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:31:26 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701117176302862123023e5f4a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:31:26 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:31:29 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:31:29 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701117176302894663575e5f4a","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:31:29 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:31:33 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:31:33 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:41:45 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176309054837103e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:41:45 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:41:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:41:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176309067127250e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:41:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:41:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:41:49 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176309089627470e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:41:49 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:41:52 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:41:52 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176309121977718e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:41:52 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:41:56 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:41:56 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:42:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176309546804554e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:42:34 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:42:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:42:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176309559164740e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:42:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:42:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:42:38 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176309581444967e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:42:38 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:42:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:42:41 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176309613765361e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:42:41 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:42:45 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:42:45 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:43:10 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176309899281055e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:43:10 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:43:11 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:43:11 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176309911601207e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:43:11 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:43:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:43:13 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176309933991424e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:43:13 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:43:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:43:16 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176309966271788e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:43:16 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:43:20 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:43:20 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:43:25 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176310050412513e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:43:25 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:43:26 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:43:26 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176310062802639e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:43:26 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:43:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:43:28 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176310085132889e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:43:28 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:43:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:43:31 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802517176310117703266e5073","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:43:31 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:43:35 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:43:35 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:44:57 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117176310972674169e4e51","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:44:57 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:44:58 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:44:58 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117176310985264348e4e51","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:44:58 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:45:00 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:45:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117176311007844538e4e51","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:45:00 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:45:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:45:04 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702117176311040514920e4e51","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:45:04 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:45:08 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:45:08 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:46:54 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802117176312142561280e6020","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:46:54 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:46:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:46:55 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802117176312155121430e6020","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:46:55 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:46:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:46:57 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802117176312177721768e6020","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:46:57 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:47:00 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:47:01 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802117176312210272216e6020","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:47:01 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:47:05 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:47:05 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:52:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702917176315202421022e4dc8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:52:00 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:52:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:52:01 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702917176315214991209e4dc8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:52:01 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:52:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:52:03 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702917176315237601466e4dc8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:52:03 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:52:06 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:52:07 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00702917176315270181810e4dc8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:52:07 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:52:11 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:52:11 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:53:16 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802e17176315966382038e5af6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:53:16 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:53:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:53:18 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802e17176315978732143e5af6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:53:18 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:53:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:53:20 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802e17176316001142410e5af6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:53:20 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:53:23 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:53:23 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802e17176316033472874e5af6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:53:23 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:53:27 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:53:27 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:53:32 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802e17176316121654178e5af6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:53:32 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:53:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:53:33 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802e17176316134074338e5af6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:53:33 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:53:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:53:35 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802e17176316156424679e5af6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:53:35 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:53:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:53:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00802e17176316188785139e5af6","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:53:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:53:43 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:53:43 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:58:33 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803517176319132016944e49cc","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:58:33 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:58:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:58:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803517176319144337123e49cc","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:58:34 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:58:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:58:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803517176319166707412e49cc","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:58:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:58:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:58:40 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803517176319199037871e49cc","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:58:40 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:58:44 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:58:44 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-05 23:59:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803517176319789396465e49cc","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:59:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:59:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-05 23:59:40 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803517176319801746615e49cc","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:59:40 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:59:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-05 23:59:42 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803517176319824136861e49cc","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:59:42 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:59:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-05 23:59:45 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803517176319856717203e49cc","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-05 23:59:45 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-05 23:59:49 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-05 23:59:49 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-06 00:00:38 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803617176320381753005e4d0e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-06 00:00:38 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-06 00:00:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-06 00:00:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803617176320394383143e4d0e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-06 00:00:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-06 00:00:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-06 00:00:41 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803617176320416943407e4d0e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-06 00:00:41 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-06 00:00:44 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-06 00:00:45 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803617176320449493814e4d0e","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-06 00:00:45 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-06 00:00:49 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-06 00:00:49 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-06 00:15:26 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-06 00:26:29 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701f17176335894305175e025d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-06 00:26:29 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-06 00:26:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-06 00:26:30 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701f17176335906665451e025d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-06 00:26:30 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-06 00:26:32 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-06-06 00:26:33 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701f17176335929225857e025d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-06 00:26:33 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-06 00:26:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-06-06 00:26:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701f17176335961546237e025d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2024-06-06 00:26:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-06-06 00:26:40 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-06-06 00:26:40 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/14881241/Deyui | デユイ - 14881241.
2024-06-06 00:33:58 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /tanNsI7f%2F889478%2F66448faa5d8a16bfb15342bfaccdd303e56ae33d%2F666103d831bffbb860e84754944e1170cf29e8a2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DAIcnxj61Y5IiYYGiJnGEEa%2FlfjKLO2zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNULYUG%2FAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ%2FRR7z23LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiidjMmPXtuMkagAFsiPqxcLtGdiAioNmt1AJZf%2BgMe0YAKxVWnQgiz8keFQcKfrfeFALd1ptZfLwjYVRjKEAXKUVR21Q0CVa2bk7fvftXq6kIxPmMRiYqy1gHGg6mypcVufAZRoVQa4Oo5I1Tg0iF4Z%2FBo9FpCMuABV8TokhM1MewzVFF%2BNnEvfX1SSAA&uploadId=3D7314446E6E445D986A4FE0E2D34429&x-oss-access-key-id=STS.NSujsEbrySJsbN8xaQgvscge9&x-oss-expires=1717637608&x-oss-signature=UFrUGsuWQ5DQQ4%2FNkonzzyJb%2B36hXsbYkwAbvdwc6L8%3D&x-oss-signature-version=OSS2
2024-06-06 00:38:38 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /xq1jA1BF%2F889478%2F628b5256595524b655d44f7d9fbd03bedc7f6409%2F666104f0a145b955acfc468b927c31f6c6816047?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DAIcnxj61Y5IiYYGiJnGEEa%2FlfjKLO2zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNULYUG%2FAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ%2FRR7z23LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiidjMmPXtuMkagAFsiPqxcLtGdiAioNmt1AJZf%2BgMe0YAKxVWnQgiz8keFQcKfrfeFALd1ptZfLwjYVRjKEAXKUVR21Q0CVa2bk7fvftXq6kIxPmMRiYqy1gHGg6mypcVufAZRoVQa4Oo5I1Tg0iF4Z%2FBo9FpCMuABV8TokhM1MewzVFF%2BNnEvfX1SSAA&uploadId=AF1D24B572EF4073A6C43C92D168AD98&x-oss-access-key-id=STS.NSujsEbrySJsbN8xaQgvscge9&x-oss-expires=1717637888&x-oss-signature=%2FPTe%2B6hRHF90t%2BrJtdT9d5gbvA14Ki9McCOuvj0qycs%3D&x-oss-signature-version=OSS2
2024-06-06 10:17:56 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-06 10:25:31 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/06/23/55/12/114009681_p0.jpg
2024-06-06 10:27:51 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /C3VsqvHB%2F889478%2F66618f08e2aaee6fd7be4adeb411fe3c5ab59cb9%2F66618f08ef5430c01c6c4cbba0401e30d5e63b7b?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bNEtv%2FiO5ywK%2BIZUTZpWQFXfpVjI7s0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNV2%2FMl3AqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew3tO8Au3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHZBNj%2FXtuMkagAFQVqfMF8XrlXmU8Zw37iu8Y0LcI6qC5pArHYdwSaSYiFtqvuGVhdTYTl1GnoMkONTK83TQgnEao%2BhPyHhIgmJA5To2Qcxb3YWnj8z8G2OnYwcJVJHVuWu8qprArlmAIMf1h79F0lOAJQhacuTYs0OmrtS9rrh8elyf0UmJuIq9PyAA&uploadId=EA8AD95232F54E3C8BBDE181E8CAF902&x-oss-access-key-id=STS.NUxYaKe1SwmcgbhAdPQuycKG3&x-oss-expires=1717673240&x-oss-signature=CJ%2BNajqtsbQwcDJxeSnQZogMQAlU5XVsmSJws2%2FKEp8%3D&x-oss-signature-version=OSS2
2024-06-06 10:54:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/03/27/16/34/15/117296870_p0.jpg
2024-06-06 11:07:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /0A2CRBBh%2F889478%2F662e2a27f2f0718e2d1345058a868498b1343bc4%2F666198582dfeace753c043c696c1b2254028fb1c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bNEtv%2FiO5ywK%2BIZUTZpWQFXfpVjI7s0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNV2%2FMl3AqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew3tO8Au3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHZBNj%2FXtuMkagAFQVqfMF8XrlXmU8Zw37iu8Y0LcI6qC5pArHYdwSaSYiFtqvuGVhdTYTl1GnoMkONTK83TQgnEao%2BhPyHhIgmJA5To2Qcxb3YWnj8z8G2OnYwcJVJHVuWu8qprArlmAIMf1h79F0lOAJQhacuTYs0OmrtS9rrh8elyf0UmJuIq9PyAA&uploadId=33FBB9DB626448A4A093899BD3F81900&x-oss-access-key-id=STS.NUxYaKe1SwmcgbhAdPQuycKG3&x-oss-expires=1717675624&x-oss-signature=3yy73iLH31L9Z9ws8VFyCQ0ihgDxc8GzYXAZwdLFXcs%3D&x-oss-signature-version=OSS2
2024-06-06 11:23:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/05/23/13/23/13/118975415_p0.png
2024-06-06 11:30:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/29/02/31/11/115574755_p0.jpg
2024-06-06 11:51:26 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/14/12/47/54/116043678_p0.jpg
2024-06-06 11:59:25 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /GFE5ffFi%2F889478%2F6525474b76e4b82af39f426193a8fe8cce40674e%2F6661a47f1e3a5f07250040feaf8d9bc60b2cbb99?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DCM8jx36UZgIWlc2HXvmhjfe1Uvr2f0Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXGEJVTAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg5gG2z3364IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16ittShm%2FXtuMkagAF%2B3HpxZ8y1ZYAqWJIGQ%2BW0UZSITwAclyDRJyvXlQJoStLNFcjVnBGoOY8V9IVLO283xfhcFOQ7SMkhJm0VkIifx8tRzog05FoqbkWAF%2FbPPerC0xDPDmwGWuKprqrsSIh4XxcUvElXprST8dLLG9Mu%2BIwUZNhnYQy4qUNHM2wMUyAA&uploadId=A160F42466824FE1880D8B4558851136&x-oss-access-key-id=STS.NSwxrE2z87GNqGfZh6qbxQx42&x-oss-expires=1717678735&x-oss-signature=eNwPrIWYF5vYRj%2FbmDsR0K%2By8qwo%2BxDDDQYUr7%2B6iEg%3D&x-oss-signature-version=OSS2
2024-06-06 12:03:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2021/02/28/22/04/57/88122653_p0.jpg
2024-06-06 22:15:29 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-06 22:30:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/05/13/07/06/05/118686468_p0.png
2024-06-06 22:41:14 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/28/12/39/11/118185738_p0.jpg
2024-06-06 23:41:16 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/08/19/56/23/115871752_p0.jpg
2024-06-07 00:14:30 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-07 00:24:29 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/01/00/02/56/117434284_p0.jpg
2024-06-07 00:26:02 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/06/07/17/31/58/108805849_p0.png
2024-06-07 10:18:11 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-07 10:21:39 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-06-07 10:21:40 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-06-07 10:30:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /sOuJdugr%2F889478%2F6662e116e089a8bf71a3467694ae9c75f2198647%2F6662e11645b6684643ac47b48a31861157ecd6c4?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bFB%2BjNiZRCwfu%2FMB7zg04bTvtGvqvNjTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVHHSzbAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnewzhNVSe364IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iuC107%2FXtuMkagAFuvqSI2Hxv1Y8bsOpaSky3Nou3HOA57HULVYjOZf0NPdk3d1rpJWf0dj7cqPG09v1GLMqQetaMNW2M1p1tKcTaMS4TkrfPDBw1ezvnaJXwcoKYR2gOIXRyEj5vKM7SN8nSna1BLa1PXLzc8POqRxK8u9Rvk2V7iQyvD4ALlXjVNiAA&uploadId=B8392CE807A74329BAE701B3A43E5156&x-oss-access-key-id=STS.NUpLRydKcv9T28BgNNBtjQnfo&x-oss-expires=1717759782&x-oss-signature=dFbfubWdxvqttJv12%2Bdi%2F%2B1gOlhaLAI3u1MGtngwmb0%3D&x-oss-signature-version=OSS2
2024-06-07 11:00:16 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/01/19/35/46/115671154_p0.jpg
2024-06-07 11:04:35 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /rrrhpcb8%2F889478%2F6625afb4e6f886f63b194088bcd54240340064fa%2F6662e9243db8b53e1af746978f3923c8b1548e98?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bFB%2BjNiZRCwfu%2FMB7zg04bTvtGvqvNjTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVHHSzbAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnewzhNVSe364IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iuC107%2FXtuMkagAFuvqSI2Hxv1Y8bsOpaSky3Nou3HOA57HULVYjOZf0NPdk3d1rpJWf0dj7cqPG09v1GLMqQetaMNW2M1p1tKcTaMS4TkrfPDBw1ezvnaJXwcoKYR2gOIXRyEj5vKM7SN8nSna1BLa1PXLzc8POqRxK8u9Rvk2V7iQyvD4ALlXjVNiAA&uploadId=F47C6BB96CB24C5F9C068D3E006DFE5E&x-oss-access-key-id=STS.NUpLRydKcv9T28BgNNBtjQnfo&x-oss-expires=1717761844&x-oss-signature=9olFfI1dZnz4voAFRC9IOkyjziRGkpcoB1qR8hP%2BHUk%3D&x-oss-signature-version=OSS2
2024-06-07 11:17:49 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/16/00/24/27/115205177_p0.png
2024-06-07 12:11:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/09/07/00/01/14/111504347_p0.jpg
2024-06-07 12:17:12 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-07 12:45:18 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /WU13FtkB%2F889478%2F66586d8c4c16f2e4f7a8495db38262d739c556a4%2F666300c090745c167d9f467eac9238593b4cbc27?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5f0fN%2FR3LBg56qBZ0%2FAllgXbuZdn7L4lDz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUDMOi3AqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQzBX9gw3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSihyDEG%2FXtuMkagAEok8Bv0Njx3WDaVrSOt%2BPJRHGzecCbzcPOkqSEQFQTDzEuIp8U5rRnV7nYA2YJQOCm%2FgY8PBMoMonPZmL5RGmTdDA4zVRvAHWI09TMfZqoleWSrKYnz%2BItqnuJfrMWy9GOdgKI35R7kuHPCcf6MR%2FjKg6dEJahWrY1CruWNQtSJyAA&uploadId=553F08584FFE4289B15D7A4EE962DB29&x-oss-access-key-id=STS.NTA7ee1oAPhjeiqrXBbiqpwSv&x-oss-expires=1717767888&x-oss-signature=QM8EZxXAz3xSUJIFb9cvhAzvr1of1MvDYv%2F3AxPKZgM%3D&x-oss-signature-version=OSS2
2024-06-07 22:16:28 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-07 22:21:19 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /B68HfsMr%2F889478%2F663c007ea3ac440f10af4274a44211b6e94a4173%2F666387c1efaf47d4f82d48e48a182b18028a8721?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bMMeD6qIpp8fSlNnHroVgwSOVdgLTdhDz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVakHCPAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2FbV5yo3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSidtSXhfXtuMkagAEVksPBQZGiSmXSoifCEAGMKEm3pw%2FNSD%2BpslMu%2BHZrPm6RR1q%2B4NEWDb2M0F1WrZtyK7CE%2BWmM0HYg4bleDUJO4JKTZgvevjNSmVtk0PIwFF%2FG6Fh7wdJ%2B%2BicVnwFbJM%2B7LlLK7YmO5A2D4nW3pek6saVm9ViASMFyflqwpPgi7SAA&uploadId=BE73C17FC0674322961678BA3A0AC28C&x-oss-access-key-id=STS.NUyzZNEUHF6N4WZEXeDjqoqvf&x-oss-expires=1717802449&x-oss-signature=OJYK7QTWLS0Z%2FwXBudEaQnyOvZE5edZz3PQwdkIEQxo%3D&x-oss-signature-version=OSS2
2024-06-07 23:13:58 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/12/01/57/12/115973454_p0.png
2024-06-08 00:15:29 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-08 10:17:19 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-08 10:42:14 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /dtRkrtMT%2F889478%2F66303105a6487e69dbe44ba18f9051511bca77f9%2F66643568c24fecc888fc4cdfb3e131bd151bb1c9?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5eDc%2Fju1ax1gaGBdEPlg3pkON8Ygr%2Flpjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNU6PYQ%2FAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ5drlAV3CbP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuiQco2F%2FXtuMkagAFnhJhsFT%2BgtQjWSJCHSOsC%2Fx7PcoiLJfT%2FY%2FerJpWrPBuXxKtrXZTbF7pyvuEZWsboBjdq7e9y0ES8dpYOdXO4FtrZLFCB1VrSYTckIfbnjCRNnmMKoM66kMCjKGWz1c8S%2Fc2U3d%2ByauBBFfbGFv5L044bN3sc3XoBs%2BvKkCfJTCAA&uploadId=942B7C324238406FA73C7429B0817808&x-oss-access-key-id=STS.NT68BZ8sT6cjveTgz14P4mzND&x-oss-expires=1717846904&x-oss-signature=bpdBenlhB2PCf7vQdAN5%2BQeQp5gix1D%2B%2Fnk8cffpyE8%3D&x-oss-signature-version=OSS2
2024-06-08 10:44:16 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /2bWWbwbX%2F889478%2F660b441cf75a1dd625f04fbfa3c42143aa3c4538%2F666435e2ee50105a2913491db0e799fe9c613d2f?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5eDc%2Fju1ax1gaGBdEPlg3pkON8Ygr%2Flpjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNU6PYQ%2FAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ5drlAV3CbP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuiQco2F%2FXtuMkagAFnhJhsFT%2BgtQjWSJCHSOsC%2Fx7PcoiLJfT%2FY%2FerJpWrPBuXxKtrXZTbF7pyvuEZWsboBjdq7e9y0ES8dpYOdXO4FtrZLFCB1VrSYTckIfbnjCRNnmMKoM66kMCjKGWz1c8S%2Fc2U3d%2ByauBBFfbGFv5L044bN3sc3XoBs%2BvKkCfJTCAA&uploadId=91C28707669B41F4B993512B80B2FCFA&x-oss-access-key-id=STS.NT68BZ8sT6cjveTgz14P4mzND&x-oss-expires=1717847026&x-oss-signature=CduQQ6u2gFNfYss0dA5y4sxlJ8Sb0ttDuvQxkhrJxrg%3D&x-oss-signature-version=OSS2
2024-06-08 10:46:46 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /p9mqddG1%2F889478%2F6662ff76a4133ccf5f0b4c528cbc75aa788b88eb%2F66643677e82c24eae03d4183b525c909b0a51dac?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5eDc%2Fju1ax1gaGBdEPlg3pkON8Ygr%2Flpjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNU6PYQ%2FAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ5drlAV3CbP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuiQco2F%2FXtuMkagAFnhJhsFT%2BgtQjWSJCHSOsC%2Fx7PcoiLJfT%2FY%2FerJpWrPBuXxKtrXZTbF7pyvuEZWsboBjdq7e9y0ES8dpYOdXO4FtrZLFCB1VrSYTckIfbnjCRNnmMKoM66kMCjKGWz1c8S%2Fc2U3d%2ByauBBFfbGFv5L044bN3sc3XoBs%2BvKkCfJTCAA&uploadId=79DE42F593414805A344AB2A33B015CC&x-oss-access-key-id=STS.NT68BZ8sT6cjveTgz14P4mzND&x-oss-expires=1717847175&x-oss-signature=IOJwSZOXwITZBk6u5%2ButCKSH7e45mgy6oYyJLVJj2aY%3D&x-oss-signature-version=OSS2
2024-06-08 11:16:14 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /jEldPlCg%2F889478%2F658179eb07d28413522e470a8feb54b5e2c2c6bb%2F66643d609a89eba86ae04e1a8a9207a37650819d?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5eDc%2Fju1ax1gaGBdEPlg3pkON8Ygr%2Flpjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNU6PYQ%2FAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ5drlAV3CbP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuiQco2F%2FXtuMkagAFnhJhsFT%2BgtQjWSJCHSOsC%2Fx7PcoiLJfT%2FY%2FerJpWrPBuXxKtrXZTbF7pyvuEZWsboBjdq7e9y0ES8dpYOdXO4FtrZLFCB1VrSYTckIfbnjCRNnmMKoM66kMCjKGWz1c8S%2Fc2U3d%2ByauBBFfbGFv5L044bN3sc3XoBs%2BvKkCfJTCAA&uploadId=3A0627E4BEC1441D8CCE0E799DDD3506&x-oss-access-key-id=STS.NT68BZ8sT6cjveTgz14P4mzND&x-oss-expires=1717848944&x-oss-signature=uHoz1UlqnLa3YsRbD%2BGCTIqu2QOs%2BgJf1T2TF84FRNI%3D&x-oss-signature-version=OSS2
2024-06-08 11:57:39 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /zsQVigks%2F889478%2F657d90572b2e4766bf8149ac90a06e811823421f%2F66644714cbd0cef643a942cb9f50697f5c4d622e?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bmE%2BPA2OpS1YeGMX7bjXMsS71ev6PRrzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNViTUAbAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew7FK0XY3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiicZlsfXtuMkagAEYm7f8aGo1waYkxyhqJ8q7Vfj3E%2BBMDxIdtW8yCk%2FFvP3Tj%2FaN9o1yzI%2BeMh64xjfhNZapK4qMk23KUg%2FYydM66BVtYtQgqbseqHkmIlPJBnLyvOzVkorO%2Bs9aZWqrRhDvtw6Ku3jaWHoaIYHvrwi8cGNJbet9FoqMeaSv1iJ1MiAA&uploadId=42C45C4A9FF84493BB6DD190E2442F5F&x-oss-access-key-id=STS.NUSXYt55sbEm3XjisyG2rPfzM&x-oss-expires=1717851428&x-oss-signature=u0TlLZND%2Beq5%2FJuCSvYrx7k3yzdE76tgA3Z5o8dG2%2FY%3D&x-oss-signature-version=OSS2
2024-06-08 12:16:21 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-08 12:39:20 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/05/08/18/00/49/118548708_p0.png
2024-06-08 13:00:04 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /SccllU5i%2F889478%2F62bc33e042b3bea53dc6414f837ae693beb1d90c%2F666455b52cf7f1e7f20946babbd8252d0a7cb290?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bmE%2BPA2OpS1YeGMX7bjXMsS71ev6PRrzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNViTUAbAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew7FK0XY3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiicZlsfXtuMkagAEYm7f8aGo1waYkxyhqJ8q7Vfj3E%2BBMDxIdtW8yCk%2FFvP3Tj%2FaN9o1yzI%2BeMh64xjfhNZapK4qMk23KUg%2FYydM66BVtYtQgqbseqHkmIlPJBnLyvOzVkorO%2Bs9aZWqrRhDvtw6Ku3jaWHoaIYHvrwi8cGNJbet9FoqMeaSv1iJ1MiAA&uploadId=5E08996754BB404ABAA912BD8EB3AEA6&x-oss-access-key-id=STS.NUSXYt55sbEm3XjisyG2rPfzM&x-oss-expires=1717855173&x-oss-signature=ZmqBXesBQGGEaaOO6gwVY44ly6DHSpwCUlqPqrqUSjQ%3D&x-oss-signature-version=OSS2
2024-06-08 13:04:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /0u7P55jp%2F889478%2F666456ca7a9d72eb87f5486f97dff0eedd3bb723%2F666456ca125654008d7445c8bc3ac07a4f92fad8?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bmE%2BPA2OpS1YeGMX7bjXMsS71ev6PRrzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNViTUAbAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew7FK0XY3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiicZlsfXtuMkagAEYm7f8aGo1waYkxyhqJ8q7Vfj3E%2BBMDxIdtW8yCk%2FFvP3Tj%2FaN9o1yzI%2BeMh64xjfhNZapK4qMk23KUg%2FYydM66BVtYtQgqbseqHkmIlPJBnLyvOzVkorO%2Bs9aZWqrRhDvtw6Ku3jaWHoaIYHvrwi8cGNJbet9FoqMeaSv1iJ1MiAA&uploadId=0281D9C85F6945C6B2A12EC7BE4C5B20&x-oss-access-key-id=STS.NUSXYt55sbEm3XjisyG2rPfzM&x-oss-expires=1717855450&x-oss-signature=J0Qawgef2giip5e2PA8DJdQ5V5wds1iggZ8Z%2BV%2Fmv7s%3D&x-oss-signature-version=OSS2
2024-06-08 13:07:06 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /QdEqZzbQ%2F889478%2F6662f3dd46f56a02371d47619f6a02d7260f3277%2F6664575c3b040b1f382a479a9e58a45e9ce00cdb?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bmE%2BPA2OpS1YeGMX7bjXMsS71ev6PRrzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNViTUAbAqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew7FK0XY3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiicZlsfXtuMkagAEYm7f8aGo1waYkxyhqJ8q7Vfj3E%2BBMDxIdtW8yCk%2FFvP3Tj%2FaN9o1yzI%2BeMh64xjfhNZapK4qMk23KUg%2FYydM66BVtYtQgqbseqHkmIlPJBnLyvOzVkorO%2Bs9aZWqrRhDvtw6Ku3jaWHoaIYHvrwi8cGNJbet9FoqMeaSv1iJ1MiAA&uploadId=BA45C14474A7431C8DCF0ACBB9B889DE&x-oss-access-key-id=STS.NUSXYt55sbEm3XjisyG2rPfzM&x-oss-expires=1717855596&x-oss-signature=aHrFbzo94uAObEfo3AocRgHCPpO1oYTjQXkdUv2hRWk%3D&x-oss-signature-version=OSS2
2024-06-08 22:15:59 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-08 22:42:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /GJRDOgYp%2F889478%2F66619783bde51439d0e04c25ae0309c2ef05f42c%2F6664de2fc085c48767294e69aead41287eba6bc1?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bfKsLDvOhyxo6bTmyCtVkXVddn1vPTszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNU7rNXS%2Fq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQzdIwEE3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiWDHLn%2FXtuMkagAF1Y3jiicrXawUlQfYQ4ZMYyuVv2459HJmyP4d9LZ0m46EzGlz%2FZIJwV94ArN6VhsCroYvi%2B5x0pAzgOCJO%2Fq1diHSLlbNulkciEt7RiM10QP0j0OO6xd1ajdlcJJoD3zu3CTIVtJv2%2BYEjw9GLPTOqy%2BRvmNSX55y8qD%2FmvIT6ySAA&uploadId=F0DCCF64D8E949E892AED557F26ABB99&x-oss-access-key-id=STS.NUjaxwQ7SqLpLJ3QYBYXK96xQ&x-oss-expires=1717890111&x-oss-signature=oVRnRY%2FNjSEQ%2BQ4xvd59qsi%2FkgMTR%2Bo2vM6IlXYHbVo%3D&x-oss-signature-version=OSS2
2024-06-08 23:03:32 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /wlumsivh%2F889478%2F66454dbb941ce8b83bef41beac2476b6c26a6571%2F6664e3263e89081f97084edeaede8091c2bf5b2e?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bfKsLDvOhyxo6bTmyCtVkXVddn1vPTszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNU7rNXS%2Fq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQzdIwEE3LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiWDHLn%2FXtuMkagAF1Y3jiicrXawUlQfYQ4ZMYyuVv2459HJmyP4d9LZ0m46EzGlz%2FZIJwV94ArN6VhsCroYvi%2B5x0pAzgOCJO%2Fq1diHSLlbNulkciEt7RiM10QP0j0OO6xd1ajdlcJJoD3zu3CTIVtJv2%2BYEjw9GLPTOqy%2BRvmNSX55y8qD%2FmvIT6ySAA&uploadId=8C7BB6C14D984E70B7F6F9C9476A17C6&x-oss-access-key-id=STS.NUjaxwQ7SqLpLJ3QYBYXK96xQ&x-oss-expires=1717891382&x-oss-signature=l3gcbXpXl1a6hN9qQfqOjj%2BS8tn5M5ugsNrfaNcJPNQ%3D&x-oss-signature-version=OSS2
2024-06-08 23:18:09 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/10/19/30/01/115929090_p0.jpg
2024-06-08 23:29:45 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /B8Mjvp1b%2F889478%2F6662e85c30df0c91dcb64f5996582547c641ab38%2F6664e94b2542fd6026ad433ba0dda74d564e32d0?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DeEePZio1yw5KcUlb%2FjngHestN1qPlpTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNU7%2FJHO%2Fq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQzfO4y03LuHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiPrCn2%2FXtuMkagAFdQqq2qdblH5r%2FYYL5YbL12HtxX8g%2B0b8vxhH40CvVquq6PW%2BeNcuArwMbwHgHuMD9HOO9DHyN1L36Lt6X%2BfLMKaA%2BrNrREgEQyc7MUxkgKIAFh%2FLlfoZsECHKEE6JJoEvn22RyoB0bEgztG7hludjRBpirbH6WhHP3qVwGVhEGSAA&uploadId=8798F6D0092347928BA7B92497BCF25B&x-oss-access-key-id=STS.NSkZYmgRStPwPpNjxRvDa9fNG&x-oss-expires=1717892955&x-oss-signature=4un%2BkxeBAno4zeVP6sWBhRfV0py63QYtflIOBE%2Fk3js%3D&x-oss-signature-version=OSS2
2024-06-08 23:44:28 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/03/15/11/33/46/116933413_p0.jpg
2024-06-09 00:15:01 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-09 00:15:54 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/06/01/00/07/12/119225736_p0.jpg
2024-06-09 10:16:43 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-09 10:53:36 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-06-09 10:53:37 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-06-09 11:23:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-06-09 11:23:53 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-06-09 11:30:40 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /S8x2MFlj%2F889478%2F6661953311a7bcd79ffc41c48d69c8984b57ad71%2F66659242c3daa49f15064e57838facf854d63eed?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5fmB%2Brh1KsY%2BoOTdFCCgVQkeP95qf392zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVbcaV%2B%2Fq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2FYW3zG364IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16ig5SaE%2FXtuMkagAGglIFxFb0dsQp94xMe%2FBb1GVfivYyjGfcSe2GRcSpC0XtioHVzE3KIZe1arpg1iB57%2BeAqqp%2B%2Fnno%2F%2F7gJ6WxcSis0kZeca6EDJJ5Sj6t76DUrN52UuacYx9X0wKt8TO6Vh%2Fqfl75ESk0L6bu98lEfEAZESmrZAGm3CHuPjoV1ayAA&uploadId=C3D4FF96EFDA43D3BDB3D01525F2EDC5&x-oss-access-key-id=STS.NTSLPU9t9MAxvv3eTqtpUF8V9&x-oss-expires=1717936210&x-oss-signature=g3BJJ2htSh5DH9E%2FEKAPU3aO9vqvZTmh8qEs4gWonWY%3D&x-oss-signature-version=OSS2
2024-06-09 12:15:44 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-09 12:34:42 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/11/12/02/22/12/113335127_p0.jpg
2024-06-09 22:16:52 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-09 22:25:13 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-06-09 22:25:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-09 22:34:28 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/29/00/06/08/116478617_p0.jpg
2024-06-09 22:47:16 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/28/00/00/26/118215399_p0.jpg
2024-06-09 23:07:15 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/13/19/54/15/115136451_p0.jpg
2024-06-09 23:15:10 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/03/05/00/00/08/116629795_p0.jpg
2024-06-09 23:43:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/29/22/52/16/118278065_p0.png
2024-06-09 23:45:24 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/20/01/01/06/116217936_p0.jpg
2024-06-10 00:09:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/22/09/20/47/112750907_p0.png
2024-06-10 00:11:26 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/01/06/18/08/14/114934650_p0.jpg
2024-06-10 00:15:53 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-10 00:40:17 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-06-10 00:40:18 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-10 10:18:59 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-10 10:22:06 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /Kbj9brEM%2F889478%2F666581dacd55ba984f834e6186b0d51a4a7606ef%2F6666d3b06168b9b868ea49ac80636e4aa88bb035?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WAG%2BnDvblz3ZKCTGDL10UvYf1Ni6fp1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVOfHDq%2Fq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew7zOX69LObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuiRk9uufXtuMkagAEbKIiAmI1HDmX6oVOIexo0C2V%2FBvlcknbJDX6Ng8cP3YJ0PNkBPD%2F%2B5zQ2kE2nozDaWT87NdsBe6mcmTCIBtojPmBh%2FeXbgXoSUp1ej%2BPZVltSwW%2B1%2BM%2BROK4b9wkuG3XYpxSfPrX8JxW5XDvTFM6zvfvbrgG1NuFKWbTa60P85SAA&uploadId=226EB4FE66C542358E4C81AE3A2C8B84&x-oss-access-key-id=STS.NV5PSwPfRjPiNFz3EzmradbB5&x-oss-expires=1718018496&x-oss-signature=v8t8HGNIKBTSxMPvjJWf7PVNt1w1rveAS2Un6NAePs8%3D&x-oss-signature-version=OSS2
2024-06-10 10:30:29 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /9b63SCpE%2F889478%2F6380ac5c56647bb1745c424eb2f531af05b91290%2F6666d5a73aed676b5f944227bc69514582d1f035?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WAG%2BnDvblz3ZKCTGDL10UvYf1Ni6fp1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVOfHDq%2Fq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew7zOX69LObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuiRk9uufXtuMkagAEbKIiAmI1HDmX6oVOIexo0C2V%2FBvlcknbJDX6Ng8cP3YJ0PNkBPD%2F%2B5zQ2kE2nozDaWT87NdsBe6mcmTCIBtojPmBh%2FeXbgXoSUp1ej%2BPZVltSwW%2B1%2BM%2BROK4b9wkuG3XYpxSfPrX8JxW5XDvTFM6zvfvbrgG1NuFKWbTa60P85SAA&uploadId=7ADE59F4BD0E46AD9C5F83201156C7AC&x-oss-access-key-id=STS.NV5PSwPfRjPiNFz3EzmradbB5&x-oss-expires=1718018999&x-oss-signature=PdUz6AgYDfhNQBRvCzXOqr1Vg17%2ByemZ5SskKT8fWnw%3D&x-oss-signature-version=OSS2
2024-06-10 11:47:09 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /tl468IxY%2F889478%2F66658975cee4231f375642de8f6c041276f721f9%2F6666e79f9f76740b466048559ccdc59ab45f0eea?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5b%2BI%2FnflZcWzYq6UUjwgFYvfM5LuZztsDz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNSHlDjG%2Fq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneUzYOhFcJ4CuHScT2d4tiNu28DlYnOfGvljlPB7uE2d6hmLfyy2qJgN%2FUMfUFq9w5A08OESGioaBesPXtuMkagAFH2IAEa6hFKUI4tJmRaOw%2FbKmgBcu%2F4tVsCR%2FGj6zBVQKcyln%2FspU8YFGZSzjMu3HYF%2B13KU%2F0AcLUlwxiWQI6wKi%2FSnCiDQUZJCKyU40fsvpnGJ7Z3rEv%2BiArwTs6%2BkM5vd71XtO50U4pNZ7OtwWp12ClFcTxEap7vvqspIHDvCAA&uploadId=783870C78955425DB27CD601C77A4F36&x-oss-access-key-id=STS.NUKhCkxH7zHQSnAdVzpAgVYFR&x-oss-expires=1718023599&x-oss-signature=27w4FeObzZgFnNvdPAuqHVxwnGKXtnSHyTIVCYsgpME%3D&x-oss-signature-version=OSS2
2024-06-10 12:17:59 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-10 22:17:29 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-10 22:32:38 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-06-10 22:32:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-10 22:34:31 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-06-10 22:34:32 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-06-10 23:03:11 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/22/17/00/05/116287411_p0.jpg
2024-06-10 23:09:38 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/06/10/00/04/49/119501784_p0.jpg
2024-06-11 00:13:01 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='www.pixiv.net', port=443): Read timed out. (read timeout=30)")': /ajax/illust/115799866
2024-06-11 00:16:30 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-11 00:17:29 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/05/12/11/46/02/118656801_p0.jpg
2024-06-11 10:19:03 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-11 10:30:05 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/11/06/12/16/115940705_p0.png
2024-06-11 10:44:40 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/10/00/00/52/114090880_p0.jpg
2024-06-11 11:19:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/05/12/11/46/02/118656801_p0.jpg
2024-06-11 12:18:03 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-11 22:15:47 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-11 22:32:40 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2024-06-11 22:32:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-06-11 23:03:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/03/18/45/35/117513446_p0.jpg
2024-06-11 23:56:20 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/03/05/00/00/08/116629795_p0.jpg
2024-06-12 00:02:18 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /pZog06ku%2F889478%2F659a911b440a7cbfcd664e0fa7bb504dc86a2389%2F6668e56ca7112ef32149478790668835c9616e7b?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5b9IvT%2FmaxD3YeFeFHipVARON8ZiqzMmzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUyXaXa%2Bq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7MMz4RLObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuils%2F6RfXtuMkagAGYwuE8yhEP9nOM4z62wISHPq0YHeSlCGu0gxUzYVZYmmtzt2MxvFZSh9DivgKeN%2B7TInMyXXm4VatoE3SX5ofiwtR8UHlnGjMY2p5vvpI0%2FMOlhulRs6Ega3wtjKM7Niyub2d9cAGS0oscXc1IzfDrY%2FNZmrHNwenbOXEJHfqrESAA&uploadId=57595102DC324C8FBCA127AB9906FCE2&x-oss-access-key-id=STS.NUHiNKtsbjEnzwSAPD4P5eigy&x-oss-expires=1718154108&x-oss-signature=9i6p16XnAn4nK2rPcE5lxzJp30avhZn%2FylH0gr8HP18%3D&x-oss-signature-version=OSS2
2024-06-12 00:14:48 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-12 00:31:04 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /bIAaz5qy%2F889478%2F6409c2ec8433ac9a54ee44459c4010de6332d2ae%2F6668ec2a82a1ebf1f82a4fcaada95a6c455a945a?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5b9IvT%2FmaxD3YeFeFHipVARON8ZiqzMmzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNUyXaXa%2Bq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneQ7MMz4RLObP7AhWvDNQ3S7jN6YihvSt3zmA4YsrdqJPW1dKDogPIx4aBwHbHMFKlwddMkwuils%2F6RfXtuMkagAGYwuE8yhEP9nOM4z62wISHPq0YHeSlCGu0gxUzYVZYmmtzt2MxvFZSh9DivgKeN%2B7TInMyXXm4VatoE3SX5ofiwtR8UHlnGjMY2p5vvpI0%2FMOlhulRs6Ega3wtjKM7Niyub2d9cAGS0oscXc1IzfDrY%2FNZmrHNwenbOXEJHfqrESAA&uploadId=B243725D53D3494693875CB4FA43EA4C&x-oss-access-key-id=STS.NUHiNKtsbjEnzwSAPD4P5eigy&x-oss-expires=1718155834&x-oss-signature=Rf%2Bw3Ktm5U9shhW71sRaYRR3Aia89qrHdBCXD84nlEQ%3D&x-oss-signature-version=OSS2
2024-06-12 10:17:58 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-12 10:56:11 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /BqLvLMoq%2F889478%2F66449e4ae704295d123140ef837389e3532c419c%2F66697ead9512791fcbb0471c8072f755867f716a?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5fbGevmqedt7vauUEj9lVAHarxErb%2FIkDz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTPgSmS%2Bq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo7xT9UXOi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iC69Fd%2FXtuMkagAF%2BpUT%2FRg1FXJgOyjra9L%2BPbFPoxviBZW2NT8nZgPKXTDaYzRD%2FvW9iNOOLGxTrBF9dbwR9e1dd4O43SFxbCIYboId9SFKDLk4RlT3EYY2DlwdNlmFlXuw0KEEjBJu7TLAct3nu352G5WIYNrdrqmJ5enBgJbhZuAzGNHeOKsHF9iAA&uploadId=D085CD610F3F4AA69AB5BF40BE9A06F7&x-oss-access-key-id=STS.NTnRQRD8LY4ERnLqPRf3hBzcr&x-oss-expires=1718193341&x-oss-signature=WpzX6NAK9HC%2Fkon7mG3v4B7DOgcN%2FYP165To2l7kG3I%3D&x-oss-signature-version=OSS2
2024-06-12 10:58:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/27/00/42/46/118186036_p0.png
2024-06-12 11:01:14 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/04/14/00/06/04/117813679_p0.jpg
2024-06-12 11:09:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/06/09/18/00/12/119487904_p0.jpg
2024-06-12 11:15:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:502:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>tfe-cloud-aso-prod-beijing-vbbcj-jspsl</td>
</tr>
<tr>
<td>Date:</td>
<td>2024/06/12 19:15:34</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2024-06-12 11:15:34 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-06-12 11:15:35 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2024-06-12 11:15:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:502:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>tfe-cloud-aso-prod-beijing-vbbcj-jspsl</td>
</tr>
<tr>
<td>Date:</td>
<td>2024/06/12 19:15:35</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2024-06-12 11:15:36 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-06-12 11:15:38 - WARNING - base.py - 25 - Retry func _post_file_complete 2 time.
2024-06-12 11:15:38 - WARNING - base.py - 100 - https://api.aliyundrive.com/v2/file/complete:502:<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>https://api.aliyundrive.com/v2/file/complete</td>
</tr>
<tr>
<td>Server:</td>
<td>tfe-cloud-aso-prod-beijing-vbbcj-jspsl</td>
</tr>
<tr>
<td>Date:</td>
<td>2024/06/12 19:15:38</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

2024-06-12 11:15:38 - ERROR - aliyundrive.py - 75 - https://api.aliyundrive.com/v2/file/complete:JsonValueError.
2024-06-12 11:15:41 - WARNING - base.py - 25 - Retry func _post_file_complete 3 time.
2024-06-12 11:20:00 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/05/26/20/36/00/119075352_p0.png
2024-06-12 11:42:20 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/10/05/09/23/25/112285582_p0.png
2024-06-12 12:16:58 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-12 12:22:54 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /BpqdHmG2%2F889478%2F65ca119adc923afdf088424c8e9cdb6ef721969d%2F66699300fd39bc90c8754651b139ff0e9c1d3a2c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bgA8nev69y9offeE7g12c4fckVnq3apzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVTzPWO%2Bq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnewzJKxivOi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i9w76S%2FXtuMkagAEgRpgRIGD7E64epotLq3nM2rhJzox8QfZeVW9gd2XlNTHgZy4FsKNqikupd1FWkOJebSRKRZvPBRUeEutWngvmDg37KwBHIi7vXd97QxncJXVGUXUuudbClc8OST9LeFhCNBNV470TrjxKNRWGcdiTW4ZN%2BOwkYcfSKwFToXCuxSAA&uploadId=1BA01C7048FB42D3B33371ACCD6C3F98&x-oss-access-key-id=STS.NUUHsjRpSAE4zhQ3gmqF9qhqE&x-oss-expires=1718198544&x-oss-signature=%2BYmN9yRC3v81k3krtPWAtCPfbgfA0AoU1Zo3so%2FQNMc%3D&x-oss-signature-version=OSS2
2024-06-12 22:16:17 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2024-06-12 22:37:17 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/06/10/19/00/03/119520267_p0.png
2024-06-12 23:32:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/02/18/00/06/00/116154271_p0.png
2024-06-12 23:52:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/05/23/12/38/13/118974771_p0.jpg
2024-06-13 00:15:19 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
