2025-03-08 23:56:00 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /eVBioyHT%2F889478%2F67c6ce8e27d1464243f140daac6cd30a9f2daf38%2F67ccd8eedb17fc49aeba4dd7a1287af05cfca078?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5fgCfnAr5xi9aGdU1HU0HkCS%2Fh%2BvIbpoDz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVrYAAXoq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2FXR7QYj7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi88UnZvXtuMkagAEmElNiBz9D%2Bv69qtnQ5vgv0Mc9hyHdXcckemwC7cm0%2BXcWM4oQ2hvrLPnLfoQ4DSkEziSYoq4zVvc4F7rkFJAnGBoVrjgWx2xZinnfipow7%2BxfnW%2FhAmYgHVIdgvnJMS5T0gANroJ0HmqoCnc%2F6kWlm4MLuEf9T2NJYqobJXSkySAA&uploadId=A83B7737AA214AFBBAAB33ECC0BF9C33&x-oss-access-key-id=STS.NTUBCtBCCBcvQwe4yWGwRSCBB&x-oss-expires=1741481726&x-oss-signature=0cPCsc6%2Br9G0uEUf%2BRkEwofgvuNh9IglDfgu0eMq6VQ%3D&x-oss-signature-version=OSS2
2025-03-09 00:06:18 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/09/05/00/00/46/122142588_p0.jpg
2025-03-09 00:08:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /dWWOQV0v%2F889478%2F67ca87586a19f0a302da447496a5b17f926cdd07%2F67ccdbde27115e0b0813403599fadd256df0774b?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5fgCfnAr5xi9aGdU1HU0HkCS%2Fh%2BvIbpoDz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVrYAAXoq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnew%2FXR7QYj7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi88UnZvXtuMkagAEmElNiBz9D%2Bv69qtnQ5vgv0Mc9hyHdXcckemwC7cm0%2BXcWM4oQ2hvrLPnLfoQ4DSkEziSYoq4zVvc4F7rkFJAnGBoVrjgWx2xZinnfipow7%2BxfnW%2FhAmYgHVIdgvnJMS5T0gANroJ0HmqoCnc%2F6kWlm4MLuEf9T2NJYqobJXSkySAA&uploadId=B99D7A5C488E4FB2A78209045374D8A1&x-oss-access-key-id=STS.NTUBCtBCCBcvQwe4yWGwRSCBB&x-oss-expires=1741482478&x-oss-signature=QRU34SovdTYb%2BQ4Whh1yyC9bz6IDrNDyccYm5aljG3Q%3D&x-oss-signature-version=OSS2
2025-03-09 00:10:26 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2025-03-09 00:22:13 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /cZhjiO5y%2F889478%2F66b758658e5635e0bc5b4e44ba8b55d641db8246%2F67ccdf16744c7d9078454e33ba019e047e00a52b?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bEMYv6ipdbgYygZX%2BCgEEifuVhm%2FHC0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNW6scwPoq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FcX0zi9i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iN7ZRwvXtuMkagAE6a8PuIeOBsG2WvinPkUGGzCqws1ShRqSk%2B66QE60iNhzbOAXVdyeluxVDwlDfKhkC5gApbXYa7w9OXIz3TYHHaApzBBMUPC2KxPoxk0G1a9T2JKf982ud07BQgv1xQ%2BQDhu4gHyapJYeal8IYyGGyfcsWhHd8HUKjq6NQkN5fEyAA&uploadId=A61BD8C7B7E24D9F83CD9A92F03145AE&x-oss-access-key-id=STS.NUqz1NgHz6NKgY3dAwrjMt4i3&x-oss-expires=1741483302&x-oss-signature=qk9XTZPBizNnligBOjj6rC60Q9AX%2Fyagj5Do%2BqPruoY%3D&x-oss-signature-version=OSS2
2025-03-09 00:24:13 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/11/30/18/08/30/124769796_p0.jpg
2025-03-09 00:27:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /0yAVy7qa%2F889478%2F66d99e900888a6adaf83419fa9390af134d9a9ff%2F67cce068f62b2e11c2af41e3bc083c194bb7700c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bEMYv6ipdbgYygZX%2BCgEEifuVhm%2FHC0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNW6scwPoq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FcX0zi9i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iN7ZRwvXtuMkagAE6a8PuIeOBsG2WvinPkUGGzCqws1ShRqSk%2B66QE60iNhzbOAXVdyeluxVDwlDfKhkC5gApbXYa7w9OXIz3TYHHaApzBBMUPC2KxPoxk0G1a9T2JKf982ud07BQgv1xQ%2BQDhu4gHyapJYeal8IYyGGyfcsWhHd8HUKjq6NQkN5fEyAA&uploadId=CD13D271E123428E9C10D3BC626FBCB4&x-oss-access-key-id=STS.NUqz1NgHz6NKgY3dAwrjMt4i3&x-oss-expires=1741483640&x-oss-signature=z3Hoh1pqvoICwvP7i0ehlAQKf6jI0BE21rzbMhSc1XQ%3D&x-oss-signature-version=OSS2
2025-03-09 00:27:54 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/0yAVy7qa%2F889478%2F66d99e900888a6adaf83419fa9390af134d9a9ff%2F67cce068f62b2e11c2af41e3bc083c194bb7700c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bEMYv6ipdbgYygZX%2BCgEEifuVhm%2FHC0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNW6scwPoq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FcX0zi9i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iN7ZRwvXtuMkagAE6a8PuIeOBsG2WvinPkUGGzCqws1ShRqSk%2B66QE60iNhzbOAXVdyeluxVDwlDfKhkC5gApbXYa7w9OXIz3TYHHaApzBBMUPC2KxPoxk0G1a9T2JKf982ud07BQgv1xQ%2BQDhu4gHyapJYeal8IYyGGyfcsWhHd8HUKjq6NQkN5fEyAA&uploadId=CD13D271E123428E9C10D3BC626FBCB4&x-oss-access-key-id=STS.NUqz1NgHz6NKgY3dAwrjMt4i3&x-oss-expires=1741483640&x-oss-signature=z3Hoh1pqvoICwvP7i0ehlAQKf6jI0BE21rzbMhSc1XQ%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67CCE08806400933330E8118</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"FADB219957C1975D532B27685DAF23F8"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-03-09 00:27:54 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/0yAVy7qa%2F889478%2F66d99e900888a6adaf83419fa9390af134d9a9ff%2F67cce068f62b2e11c2af41e3bc083c194bb7700c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bEMYv6ipdbgYygZX%2BCgEEifuVhm%2FHC0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNW6scwPoq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FcX0zi9i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iN7ZRwvXtuMkagAE6a8PuIeOBsG2WvinPkUGGzCqws1ShRqSk%2B66QE60iNhzbOAXVdyeluxVDwlDfKhkC5gApbXYa7w9OXIz3TYHHaApzBBMUPC2KxPoxk0G1a9T2JKf982ud07BQgv1xQ%2BQDhu4gHyapJYeal8IYyGGyfcsWhHd8HUKjq6NQkN5fEyAA&uploadId=CD13D271E123428E9C10D3BC626FBCB4&x-oss-access-key-id=STS.NUqz1NgHz6NKgY3dAwrjMt4i3&x-oss-expires=1741483640&x-oss-signature=z3Hoh1pqvoICwvP7i0ehlAQKf6jI0BE21rzbMhSc1XQ%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67CCE08AB8F87735397146C8</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"FADB219957C1975D532B27685DAF23F8"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-03-09 00:27:55 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/0yAVy7qa%2F889478%2F66d99e900888a6adaf83419fa9390af134d9a9ff%2F67cce068f62b2e11c2af41e3bc083c194bb7700c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bEMYv6ipdbgYygZX%2BCgEEifuVhm%2FHC0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNW6scwPoq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FcX0zi9i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iN7ZRwvXtuMkagAE6a8PuIeOBsG2WvinPkUGGzCqws1ShRqSk%2B66QE60iNhzbOAXVdyeluxVDwlDfKhkC5gApbXYa7w9OXIz3TYHHaApzBBMUPC2KxPoxk0G1a9T2JKf982ud07BQgv1xQ%2BQDhu4gHyapJYeal8IYyGGyfcsWhHd8HUKjq6NQkN5fEyAA&uploadId=CD13D271E123428E9C10D3BC626FBCB4&x-oss-access-key-id=STS.NUqz1NgHz6NKgY3dAwrjMt4i3&x-oss-expires=1741483640&x-oss-signature=z3Hoh1pqvoICwvP7i0ehlAQKf6jI0BE21rzbMhSc1XQ%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67CCE08A31A0343431BE313B</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"FADB219957C1975D532B27685DAF23F8"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-03-09 00:27:55 - ERROR - aliyundrive.py - 1077 - File tmp/120992121/120992121_p0.png Part 1 upload failed.
2025-03-09 00:35:16 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /g1jjiQEQ%2F889478%2F6779c0f4aee551e1f0cd4da384439bcd81766f71%2F67cce2269e132880b2ae476487ffd26fad268125?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bEMYv6ipdbgYygZX%2BCgEEifuVhm%2FHC0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNW6scwPoq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FcX0zi9i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iN7ZRwvXtuMkagAE6a8PuIeOBsG2WvinPkUGGzCqws1ShRqSk%2B66QE60iNhzbOAXVdyeluxVDwlDfKhkC5gApbXYa7w9OXIz3TYHHaApzBBMUPC2KxPoxk0G1a9T2JKf982ud07BQgv1xQ%2BQDhu4gHyapJYeal8IYyGGyfcsWhHd8HUKjq6NQkN5fEyAA&uploadId=C7CF77F270504456891E4D3E424456E8&x-oss-access-key-id=STS.NUqz1NgHz6NKgY3dAwrjMt4i3&x-oss-expires=1741484086&x-oss-signature=qzPRJYBU%2BP6wV%2F0wWboOVujB8cPLt4JUItpSDwOjtqM%3D&x-oss-signature-version=OSS2
2025-03-09 00:37:19 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /HkP3f0Uq%2F889478%2F6763cee6fd649d2af9664a48932a7af76e95575c%2F67cce2a1258dcd87142d4bee8dd5d5a4da391f2f?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bEMYv6ipdbgYygZX%2BCgEEifuVhm%2FHC0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNW6scwPoq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FcX0zi9i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iN7ZRwvXtuMkagAE6a8PuIeOBsG2WvinPkUGGzCqws1ShRqSk%2B66QE60iNhzbOAXVdyeluxVDwlDfKhkC5gApbXYa7w9OXIz3TYHHaApzBBMUPC2KxPoxk0G1a9T2JKf982ud07BQgv1xQ%2BQDhu4gHyapJYeal8IYyGGyfcsWhHd8HUKjq6NQkN5fEyAA&uploadId=92EAEDBDBB2D45419C80B91ED3F18636&x-oss-access-key-id=STS.NUqz1NgHz6NKgY3dAwrjMt4i3&x-oss-expires=1741484209&x-oss-signature=rQcpIPL%2BShNu6uvXw8kSwLH6S5F%2B70910wZ%2FgckoYJs%3D&x-oss-signature-version=OSS2
2025-03-09 00:37:50 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /HkP3f0Uq%2F889478%2F6763cee6fd649d2af9664a48932a7af76e95575c%2F67cce2a1258dcd87142d4bee8dd5d5a4da391f2f?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bEMYv6ipdbgYygZX%2BCgEEifuVhm%2FHC0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNW6scwPoq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FcX0zi9i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iN7ZRwvXtuMkagAE6a8PuIeOBsG2WvinPkUGGzCqws1ShRqSk%2B66QE60iNhzbOAXVdyeluxVDwlDfKhkC5gApbXYa7w9OXIz3TYHHaApzBBMUPC2KxPoxk0G1a9T2JKf982ud07BQgv1xQ%2BQDhu4gHyapJYeal8IYyGGyfcsWhHd8HUKjq6NQkN5fEyAA&uploadId=92EAEDBDBB2D45419C80B91ED3F18636&x-oss-access-key-id=STS.NUqz1NgHz6NKgY3dAwrjMt4i3&x-oss-expires=1741484209&x-oss-signature=rQcpIPL%2BShNu6uvXw8kSwLH6S5F%2B70910wZ%2FgckoYJs%3D&x-oss-signature-version=OSS2
2025-03-09 00:39:26 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /jS8ggEkv%2F889478%2F676d0105d674720cd11240328248af3d662fe806%2F67cce3201dcdb9c424d6410b84b79f86991e727b?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bEMYv6ipdbgYygZX%2BCgEEifuVhm%2FHC0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNW6scwPoq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FcX0zi9i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iN7ZRwvXtuMkagAE6a8PuIeOBsG2WvinPkUGGzCqws1ShRqSk%2B66QE60iNhzbOAXVdyeluxVDwlDfKhkC5gApbXYa7w9OXIz3TYHHaApzBBMUPC2KxPoxk0G1a9T2JKf982ud07BQgv1xQ%2BQDhu4gHyapJYeal8IYyGGyfcsWhHd8HUKjq6NQkN5fEyAA&uploadId=CF56ED5F333C4275BD6F213B52D512BE&x-oss-access-key-id=STS.NUqz1NgHz6NKgY3dAwrjMt4i3&x-oss-expires=1741484336&x-oss-signature=vuP7WfdmxcKv%2FvT5wO88ik1R%2Ff5FtBHNHLSsjv1VbIQ%3D&x-oss-signature-version=OSS2
2025-03-09 00:49:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /f8ty3HmG%2F889478%2F65c4c4b52114520158eb4b2aa69aa878eae201ff%2F67cce57379968b1b6cd34f22854011d0f4b704a1?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5bEMYv6ipdbgYygZX%2BCgEEifuVhm%2FHC0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNW6scwPoq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FcX0zi9i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iN7ZRwvXtuMkagAE6a8PuIeOBsG2WvinPkUGGzCqws1ShRqSk%2B66QE60iNhzbOAXVdyeluxVDwlDfKhkC5gApbXYa7w9OXIz3TYHHaApzBBMUPC2KxPoxk0G1a9T2JKf982ud07BQgv1xQ%2BQDhu4gHyapJYeal8IYyGGyfcsWhHd8HUKjq6NQkN5fEyAA&uploadId=56C34531370645DDB76A07724379DE48&x-oss-access-key-id=STS.NUqz1NgHz6NKgY3dAwrjMt4i3&x-oss-expires=1741484931&x-oss-signature=B%2F80nqJnRh5i3S2PlvC6HUAv2f9Q8TJBdBKXV%2F3TFj0%3D&x-oss-signature-version=OSS2
2025-03-09 22:12:02 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2025-03-09 22:48:25 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/03/10/00/00/45/116774341_p0.jpg
2025-03-09 22:55:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2022/10/27/00/12/21/102257565_p0.jpg
2025-03-09 22:57:54 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/10/31/16/06/44/123850078_p0.jpg
2025-03-09 23:00:59 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2025/02/17/12/02/55/127342279_p0.jpg
2025-03-09 23:07:22 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/10/12/18/38/02/123262497_p0.jpg
2025-03-09 23:14:00 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/08/21/21/01/08/121704809_p0.png
2025-03-10 00:09:48 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/10/12/21/26/51/123267731_p0.png
2025-03-10 00:11:02 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2025-03-10 00:19:04 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/03/24/01/40/54/117192866_p0.jpg
2025-03-10 00:27:21 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/12/07/20/19/16/124980334_p0.jpg
2025-03-10 00:33:48 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2025/01/20/00/00/23/126384311_p0.png
2025-03-10 00:41:15 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/12/01/00/03/15/124782976_p0.png
2025-03-10 00:42:04 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /JxK5FBpT%2F889478%2F67a6ed66b721ea5e13ea45d191bad28dbf76b3ec%2F67ce353d295d554a64c44878ab7b2f69796e0370?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5b4JPmB26hnxaDaW3X0jXVifv98v%2FTulTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNVf0CFXnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYnewz7U6QMj7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiCpmEEfXtuMkagAFdsb51k5JPYwAa3Wsrp3pH%2FcU0DKyTwlsL%2FxcJhVE02zeAA28AtReT%2BZfnW6Nod5SVhpensuO5w346N7%2BNPFUVjJW%2BdA8wJEVLDJUlrec8Kgly3yePSFboVz1kYZHAzxz%2F%2FFYZOLtXRW%2BS1lw06orpJBoDtltTDq2Sms1TF6dd%2FSAA&uploadId=200B743AF7174994A17F2C058E4E58EB&x-oss-access-key-id=STS.NUMoC56wFrb1YSEiu7rpPP1Ew&x-oss-expires=1741570893&x-oss-signature=qjhDDYB4TGyjOEm0VX2q0AbIvLoTAq1A%2Bi4RTrsFXZ4%3D&x-oss-signature-version=OSS2
2025-03-10 22:13:45 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2025-03-10 22:34:06 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /ajax/illust/126006338/pages
2025-03-10 22:45:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /ajax/illust/126386461
2025-03-10 22:56:01 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2025/01/11/01/51/29/126098716_p0.jpg
2025-03-10 23:02:07 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/11/24/11/18/26/124584054_p0.jpg
2025-03-10 23:16:16 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/12/05/00/00/19/124901887_p0.jpg
2025-03-10 23:16:43 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2025/01/04/20/08/41/125898559_p0.png
2025-03-11 00:12:46 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2025-03-11 00:18:04 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /JKNoZY8p%2F889478%2F65cdf3e585a294c0a4c04d25bd73771d9724b612%2F67cf811eba6d67c4b61d4ce89b7c1d71b729ce4a?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5WGfs7trKxC77jecXbl12QHO8MUir%2BY1Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXWoPzfnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3pQXgfFi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iBj%2FRzvXtuMkagAEJvqvpnTwmBUbQMFIt1VMvAZYCUbxLbAZ2UkVGOFePa%2FXFai5RMTnx0JQiLS9JLHr8ZOfIqF6KI%2BufbZjK7zKk9wYtBlNtnAU4TDiXw12z9ixjgQT8SLAL93VjR1Vbzi0sr9gE350f9CXzNAa8gTxvOpJZA%2FCdF9IHAwWtsU%2FAiSAA&uploadId=82C7FAEC8A7E4124BD7AD60F01A2D4C8&x-oss-access-key-id=STS.NV35tYAscXz5sPT3dR7L8ez37&x-oss-expires=1741655854&x-oss-signature=4bIHAlV3DND51zWlP2V1divb%2BkFGYD1C%2FO%2FfSNqFGiQ%3D&x-oss-signature-version=OSS2
2025-03-11 00:26:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /tYJu2nv9%2F889478%2F660e9b866f2068fdd3c540adbab00439adef9661%2F67cf8332621041b484ce4c6ba9728e62b8adccf1?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5b2et78n61vw5vSZ2OGhksFTcNDi7Gajzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTCwLi7nq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo3BS%2FHzT7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiK%2F3rifXtuMkagAFn1oUtITL0wqj1t8XvK55xtpdiE8S%2FCLSYlKDOBSzB1w5qXW3tLWkc20vWTEAnqilhHrKJAhi9YrM2Yt7O2iRoxcCCi5a6fz%2Bb44DUBGELmY9iPlN7TsBUpFYqpcmn6XFYSSkNIz4SX8008xpi1CKLwLyzDzabQxQmip9LSUOQKSAA&uploadId=42D75FAA76A045DE904335BC2741E0FB&x-oss-access-key-id=STS.NUC1dHrrNtY9eE7bKPALodt1m&x-oss-expires=1741656386&x-oss-signature=2Qq6qlGc5mrI%2BdJALPFsYxGKVEdYlxgCrXLUwmGvHCE%3D&x-oss-signature-version=OSS2
2025-03-11 00:33:51 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /0MH5n8Ck%2F889478%2F66a8d1cf7ad7529afb1948a7924f5d8f5ff46061%2F67cf84d13a6dbd4bceb84823b45cc5543c66a079?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5b2et78n61vw5vSZ2OGhksFTcNDi7Gajzz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTCwLi7nq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo3BS%2FHzT7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiK%2F3rifXtuMkagAFn1oUtITL0wqj1t8XvK55xtpdiE8S%2FCLSYlKDOBSzB1w5qXW3tLWkc20vWTEAnqilhHrKJAhi9YrM2Yt7O2iRoxcCCi5a6fz%2Bb44DUBGELmY9iPlN7TsBUpFYqpcmn6XFYSSkNIz4SX8008xpi1CKLwLyzDzabQxQmip9LSUOQKSAA&uploadId=4E9A85936C444089B93C05D8A7CB00CC&x-oss-access-key-id=STS.NUC1dHrrNtY9eE7bKPALodt1m&x-oss-expires=1741656801&x-oss-signature=0RAnIoDpo%2F%2B%2F6cuyiHAIK7excJPCdG0tssWVpF%2BDk3Y%3D&x-oss-signature-version=OSS2
2025-03-11 00:37:12 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/06/05/00/00/28/119350692_p0.jpg
