2025-04-07 07:46:50 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017440120099037497e0dff","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 07:46:50 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 07:46:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 07:46:53 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017440120131887812e0dff","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 07:46:53 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 07:46:57 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 07:46:57 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 07:52:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /ocSrO8XL%2F889478%2F67555d001862da493404497abb3f786a8088edcf%2F67f3842b5c2b50abeccb43beb3fe4ff378e209ec?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=B7D2924E109A4D0AA7E8DAA00CF67566&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744015931&x-oss-signature=609KGIiWWefMb736F%2FtwgHGsox2ErUCoGHcNS0PzMn0%3D&x-oss-signature-version=OSS2
2025-04-07 07:55:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017440125365943752e0de7","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 07:55:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 07:55:37 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 07:55:38 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017440125378653980e0de7","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 07:55:38 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 07:55:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 07:55:40 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017440125401334292e0de7","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 07:55:40 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 07:55:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 07:55:43 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017440125434004849e0de7","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 07:55:43 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 07:55:47 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 07:55:47 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 08:01:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /FM4Iie4r%2F889478%2F64f1be8bc141db99372e4750b41b05a912a86d00%2F67f3863f2186a828d9b540ea86f933c807a17af2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=DBB04514DBB842B38313EA8DE5EEF27B&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744016463&x-oss-signature=voRs%2B8xIH6nWyS6xrplmSxHMLSgMfO52a2wNlLAES6I%3D&x-oss-signature-version=OSS2
2025-04-07 08:08:53 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /GtzpHdXR%2F889478%2F67e0fc4e7c4f961ed4044178885713b27f84ed22%2F67f387f5a92e630302dc497b9e03a7e190989fa9?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=861C10A803DC47F398D4D9410C2B97CC&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744016902&x-oss-signature=7A%2F2%2FSN9X2dxGfUlIVX%2Bb52iBM9A1PGj8%2FOwF%2BrV%2B34%3D&x-oss-signature-version=OSS2
2025-04-07 08:11:29 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/10/14/17/00/04/123325996_p0.png
2025-04-07 08:12:02 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /datEAXv0%2F889478%2F672102e7ced57f19ea9040f089405ecd1928d0d2%2F67f388b4827458c70695421fa58ed9a0a327c0be?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=712A70FD1E1E49A99083E2ED28BDD16B&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744017092&x-oss-signature=zbPgTZ%2B4fI0rvNqZQ93C6PTft7gWUIYZb24u6Cfvsqs%3D&x-oss-signature-version=OSS2
2025-04-07 08:12:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /datEAXv0%2F889478%2F672102e7ced57f19ea9040f089405ecd1928d0d2%2F67f388b4827458c70695421fa58ed9a0a327c0be?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=712A70FD1E1E49A99083E2ED28BDD16B&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744017092&x-oss-signature=zbPgTZ%2B4fI0rvNqZQ93C6PTft7gWUIYZb24u6Cfvsqs%3D&x-oss-signature-version=OSS2
2025-04-07 08:15:31 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017440137314788589e0de7","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:15:31 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:15:32 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 08:15:32 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017440137327418809e0de7","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:15:32 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:15:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 08:15:35 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017440137350061242e0de7","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:15:35 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:15:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 08:15:38 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701017440137382701856e0de7","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:15:38 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:15:42 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 08:15:42 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 08:17:12 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701617440138325106575e2879","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:17:12 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:17:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 08:17:13 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701617440138337796743e2879","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:17:13 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:17:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 08:17:16 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701617440138360457119e2879","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:17:16 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:17:19 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 08:17:19 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701617440138393137622e2879","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:17:19 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:17:23 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 08:17:23 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 08:24:29 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /a3gpyJ0R%2F889478%2F61f40b430524f9acf4de4db8a2b91fb14aafdbb8%2F67f38b9e051649c33b0c476fb07f1c4500e023ab?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=6AE8670076C84E6F9F8BDBE96AF1509F&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744017838&x-oss-signature=LC%2Bpm6qYRt4003gcJiaKpSmophVq7GmZ%2Bf8YqPxLqCY%3D&x-oss-signature-version=OSS2
2025-04-07 08:32:07 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /gJ7QPVlW%2F889478%2F65992f228c8b8c75425f46eeb4d650b05a83adbb%2F67f38d696a62aff368004ddbac51f57e90975699?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=6CE894F5462344898E1CDDB62B2FD329&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744018297&x-oss-signature=u3aTfWSRJ7IdhjZ5ijatAZWsSTLr%2F2DxQ32Zt3%2BiQhg%3D&x-oss-signature-version=OSS2
2025-04-07 08:40:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801617440152395414921ea054","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:40:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:40:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 08:40:40 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801617440152408035154ea054","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:40:40 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:40:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 08:40:43 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801617440152430695592ea054","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:40:43 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:40:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 08:40:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801617440152463366100ea054","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:40:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:40:50 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 08:40:50 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 08:41:52 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /unzARqGt%2F889478%2F66bb4c9aad4b78267624494287d56b752a2c43bd%2F67f38fad4deae03869f34895bafa78c36819f4c6?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=2FC5CDAC9520419EB33A7FF018C87EC3&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744018877&x-oss-signature=YNQJu2aVW9kI04qiQ067q7dXGFYyBQ%2BwnSesAu6XRKs%3D&x-oss-signature-version=OSS2
2025-04-07 08:41:55 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/unzARqGt%2F889478%2F66bb4c9aad4b78267624494287d56b752a2c43bd%2F67f38fad4deae03869f34895bafa78c36819f4c6?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=2FC5CDAC9520419EB33A7FF018C87EC3&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744018877&x-oss-signature=YNQJu2aVW9kI04qiQ067q7dXGFYyBQ%2BwnSesAu6XRKs%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67F38FD14A53963238B2AA4A</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"7E0806F2F4DA64D21C2E5388A3F20190"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-04-07 08:41:55 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/unzARqGt%2F889478%2F66bb4c9aad4b78267624494287d56b752a2c43bd%2F67f38fad4deae03869f34895bafa78c36819f4c6?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=2FC5CDAC9520419EB33A7FF018C87EC3&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744018877&x-oss-signature=YNQJu2aVW9kI04qiQ067q7dXGFYyBQ%2BwnSesAu6XRKs%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67F38FD390168836318B1401</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"7E0806F2F4DA64D21C2E5388A3F20190"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-04-07 08:41:58 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/unzARqGt%2F889478%2F66bb4c9aad4b78267624494287d56b752a2c43bd%2F67f38fad4deae03869f34895bafa78c36819f4c6?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=2FC5CDAC9520419EB33A7FF018C87EC3&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744018877&x-oss-signature=YNQJu2aVW9kI04qiQ067q7dXGFYyBQ%2BwnSesAu6XRKs%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67F38FD3ACC65C3630681D4B</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"7E0806F2F4DA64D21C2E5388A3F20190"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-04-07 08:41:58 - ERROR - aliyundrive.py - 1077 - File tmp/121307604/121307604_p0.jpg Part 1 upload failed.
2025-04-07 08:45:37 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817440155374353054e0331","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:45:37 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:45:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 08:45:38 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817440155387053232e0331","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:45:38 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:45:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 08:45:41 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817440155409653649e0331","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:45:41 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:45:44 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 08:45:44 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817440155442274350e0331","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:45:44 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:45:48 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 08:45:48 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 08:49:00 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /ErTwOtuA%2F889478%2F675fd9279c98fbd0f33e4602b39f9899ccb49037%2F67f3915e9e8006895bc747d2a86865b4cd22fb6c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=8FCE28EF22784795B936C81724088835&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744019310&x-oss-signature=UDX%2B5nzWE0DsgjGxHbuW5YBSJlJdapj7kaZ6QJyYoJM%3D&x-oss-signature-version=OSS2
2025-04-07 08:52:14 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060e017440159340133409ed151","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:52:14 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:52:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 08:52:15 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060e017440159352813715ed151","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:52:15 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:52:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 08:52:17 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060e017440159375554118ed151","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:52:17 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:52:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 08:52:21 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060e017440159408314833ed151","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:52:21 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:52:25 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 08:52:25 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 08:55:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00617440160998871723e7ab0","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:55:00 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:55:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 08:55:01 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00617440161011491899e7ab0","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:55:01 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:55:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 08:55:03 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00617440161034142186e7ab0","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:55:03 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:55:06 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 08:55:06 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00617440161066992571e7ab0","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 08:55:06 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 08:55:10 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 08:55:10 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 09:02:39 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /Kc2tppaB%2F889478%2F6791d2a987f84f27300b4a9b928f91e964f9114b%2F67f39478638378551abb4182815b5b6e6128491c?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=6FA9C4CB666B41F99E766BBE6DA52BD5&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744020104&x-oss-signature=NttlSddIgorNcSYpLnk4E3pY47BakOrAt%2FFVFtmh5Pk%3D&x-oss-signature-version=OSS2
2025-04-07 09:11:29 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /5ZOwtrCT%2F889478%2F67a999c03088f0716c3249fcac8a7a187c9a1d06%2F67f396a3b899f14b3f564f3289a540c8cacc0b1d?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=7851D609A5404E2982935A517775BBAE&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744020659&x-oss-signature=2OkEjlm%2BXQWcx2Uc0%2BsKHg%2BZZwfRvVTm7p2WHVdwwyg%3D&x-oss-signature-version=OSS2
2025-04-07 09:11:39 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/5ZOwtrCT%2F889478%2F67a999c03088f0716c3249fcac8a7a187c9a1d06%2F67f396a3b899f14b3f564f3289a540c8cacc0b1d?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=7851D609A5404E2982935A517775BBAE&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744020659&x-oss-signature=2OkEjlm%2BXQWcx2Uc0%2BsKHg%2BZZwfRvVTm7p2WHVdwwyg%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67F396C2862AE63539EF07E0</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"30B63C640B13B50F30C91AFD058540DF"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-04-07 09:11:42 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/5ZOwtrCT%2F889478%2F67a999c03088f0716c3249fcac8a7a187c9a1d06%2F67f396a3b899f14b3f564f3289a540c8cacc0b1d?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=7851D609A5404E2982935A517775BBAE&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744020659&x-oss-signature=2OkEjlm%2BXQWcx2Uc0%2BsKHg%2BZZwfRvVTm7p2WHVdwwyg%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67F396CBAE116D3930A8EE94</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"30B63C640B13B50F30C91AFD058540DF"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-04-07 09:11:44 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/5ZOwtrCT%2F889478%2F67a999c03088f0716c3249fcac8a7a187c9a1d06%2F67f396a3b899f14b3f564f3289a540c8cacc0b1d?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=7851D609A5404E2982935A517775BBAE&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744020659&x-oss-signature=2OkEjlm%2BXQWcx2Uc0%2BsKHg%2BZZwfRvVTm7p2WHVdwwyg%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>67F396CE862AE63539B623E0</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"30B63C640B13B50F30C91AFD058540DF"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2025-04-07 09:11:44 - ERROR - aliyundrive.py - 1077 - File tmp/126825722_mirage/126825722_p2.png Part 1 upload failed.
2025-04-07 09:15:02 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/115826259:404:{"error":true,"message":"","body":[]}
2025-04-07 09:15:02 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/115826259:No msg.
2025-04-07 09:15:03 - WARNING - base.py - 25 - Retry func _get_illust 1 time.
2025-04-07 09:15:03 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/115826259:404:{"error":true,"message":"","body":[]}
2025-04-07 09:15:03 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/115826259:No msg.
2025-04-07 09:15:05 - WARNING - base.py - 25 - Retry func _get_illust 2 time.
2025-04-07 09:15:06 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/115826259:404:{"error":true,"message":"","body":[]}
2025-04-07 09:15:06 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/115826259:No msg.
2025-04-07 09:15:09 - WARNING - base.py - 25 - Retry func _get_illust 3 time.
2025-04-07 09:15:09 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/115826259:404:{"error":true,"message":"","body":[]}
2025-04-07 09:15:09 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/115826259:No msg.
2025-04-07 09:15:13 - ERROR - base.py - 36 - All retries failed in func _get_illust.
2025-04-07 09:15:13 - ERROR - pixiv.py - 550 - Failed to get 115826259 illust info.
2025-04-07 09:19:22 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2025-04-07 09:25:42 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /Fqcsb1J3%2F889478%2F6576e50c1cc0044d3aba4a2989bb4ba196006359%2F67f399f87b885adfe9d1424c8d6c99b7f4ceeffe?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=4B7FFBF4968E41B29DA60C2E8DDA4A87&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744021512&x-oss-signature=1sjPS0fwJZlt87FmYCBMa2Av1wdvCe4TmtPqMnrkvuY%3D&x-oss-signature-version=OSS2
2025-04-07 09:30:21 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700917440182208497484e0cd0","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:30:21 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:30:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 09:30:22 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700917440182221397671e0cd0","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:30:22 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:30:24 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 09:30:24 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700917440182243988012e0cd0","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:30:24 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:30:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 09:30:27 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700917440182277088587e0cd0","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:30:27 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:30:31 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 09:30:31 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 09:31:50 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/115537354:404:{"error":true,"message":"","body":[]}
2025-04-07 09:31:50 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/115537354:No msg.
2025-04-07 09:31:51 - WARNING - base.py - 25 - Retry func _get_illust 1 time.
2025-04-07 09:31:52 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/115537354:404:{"error":true,"message":"","body":[]}
2025-04-07 09:31:52 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/115537354:No msg.
2025-04-07 09:31:54 - WARNING - base.py - 25 - Retry func _get_illust 2 time.
2025-04-07 09:31:54 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/115537354:404:{"error":true,"message":"","body":[]}
2025-04-07 09:31:54 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/115537354:No msg.
2025-04-07 09:31:57 - WARNING - base.py - 25 - Retry func _get_illust 3 time.
2025-04-07 09:31:57 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/115537354:404:{"error":true,"message":"","body":[]}
2025-04-07 09:31:57 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/115537354:No msg.
2025-04-07 09:32:01 - ERROR - base.py - 36 - All retries failed in func _get_illust.
2025-04-07 09:32:01 - ERROR - pixiv.py - 550 - Failed to get 115537354 illust info.
2025-04-07 09:38:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /fvCQKckQ%2F889478%2F67a475e2a33a29e502774ef1a8cf8c0c38003f0b%2F67f39cf8c1a326a148d9440c82ca893afef40a82?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5XRHtH1vZF5%2BbWlW0nip2dnbftanonuszz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNTrJEUreq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneo%2FXAz2fP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSi2JQLrfXtuMkagAGWutGcG11UHx73u2fif365wwanWwIl4F2A%2FMtsJ7pHh0dheQwXeW2Y%2F3uRHInTWthQfg35yZoT%2Blsbi0vIm2MYkAuDXyfrI2QpWzd8flQy%2Bg0%2FxdGnXsMuoqvPbSiETtpKENQgKo%2FTD63b9QB9HL36JBT6O3F3yMPir0KaTeIb8yAA&uploadId=9FB0F87844084F609913288444F30DCA&x-oss-access-key-id=STS.NVdUkAPNXNwNYoSCg2atvqLEQ&x-oss-expires=1744022280&x-oss-signature=IkPUXhDIA9ADhAg4rd8c7X1qXr0nUUjc24T4eXsn7c4%3D&x-oss-signature-version=OSS2
2025-04-07 09:39:03 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440187430777701efcb9","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:39:03 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:39:04 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 09:39:04 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440187443467820efcb9","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:39:04 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:39:06 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 09:39:06 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440187466218038efcb9","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:39:06 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:39:09 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 09:39:10 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440187498928405efcb9","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:39:10 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:39:14 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 09:39:14 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 09:39:23 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/114766733:404:{"error":true,"message":"","body":[]}
2025-04-07 09:39:23 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/114766733:No msg.
2025-04-07 09:39:24 - WARNING - base.py - 25 - Retry func _get_illust 1 time.
2025-04-07 09:39:24 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/114766733:404:{"error":true,"message":"","body":[]}
2025-04-07 09:39:24 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/114766733:No msg.
2025-04-07 09:39:26 - WARNING - base.py - 25 - Retry func _get_illust 2 time.
2025-04-07 09:39:27 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/114766733:404:{"error":true,"message":"","body":[]}
2025-04-07 09:39:27 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/114766733:No msg.
2025-04-07 09:39:30 - WARNING - base.py - 25 - Retry func _get_illust 3 time.
2025-04-07 09:39:30 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/114766733:404:{"error":true,"message":"","body":[]}
2025-04-07 09:39:30 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/114766733:No msg.
2025-04-07 09:39:34 - ERROR - base.py - 36 - All retries failed in func _get_illust.
2025-04-07 09:39:34 - ERROR - pixiv.py - 550 - Failed to get 114766733 illust info.
2025-04-07 09:41:14 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00617440188746816005e7aa6","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:41:14 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:41:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 09:41:16 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00617440188759446107e7aa6","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:41:16 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:41:18 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 09:41:18 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00617440188782066313e7aa6","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:41:18 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:41:21 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 09:41:21 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00617440188814686578e7aa6","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:41:21 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:41:25 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 09:41:25 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 09:42:37 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817440189576631464e0330","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:42:37 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:42:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 09:42:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817440189589501674e0330","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:42:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:42:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 09:42:41 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817440189612112022e0330","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:42:41 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:42:44 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 09:42:44 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817440189644732402e0330","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:42:44 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:42:48 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 09:42:48 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 09:45:32 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00317440191327948528ed3cf","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:45:32 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:45:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 09:45:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00317440191340578692ed3cf","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:45:34 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:45:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 09:45:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00317440191363431004ed3cf","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:45:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:45:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 09:45:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00317440191396101493ed3cf","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 09:45:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 09:45:43 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 09:45:43 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 09:46:55 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/116810101:404:{"error":true,"message":"","body":[]}
2025-04-07 09:46:55 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/116810101:No msg.
2025-04-07 09:46:56 - WARNING - base.py - 25 - Retry func _get_illust 1 time.
2025-04-07 09:46:57 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/116810101:404:{"error":true,"message":"","body":[]}
2025-04-07 09:46:57 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/116810101:No msg.
2025-04-07 09:46:59 - WARNING - base.py - 25 - Retry func _get_illust 2 time.
2025-04-07 09:46:59 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/116810101:404:{"error":true,"message":"","body":[]}
2025-04-07 09:46:59 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/116810101:No msg.
2025-04-07 09:47:02 - WARNING - base.py - 25 - Retry func _get_illust 3 time.
2025-04-07 09:47:02 - WARNING - base.py - 100 - https://www.pixiv.net/ajax/illust/116810101:404:{"error":true,"message":"","body":[]}
2025-04-07 09:47:02 - ERROR - pixiv.py - 114 - https://www.pixiv.net/ajax/illust/116810101:No msg.
2025-04-07 09:47:06 - ERROR - base.py - 36 - All retries failed in func _get_illust.
2025-04-07 09:47:06 - ERROR - pixiv.py - 550 - Failed to get 116810101 illust info.
2025-04-07 09:47:18 - WARNING - pixivdrive.py - 219 - Failed to upload some user top illusts.
2025-04-07 22:14:45 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2025-04-07 22:19:32 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00600417440643726943698e3999","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:19:32 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:19:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 22:19:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00600417440643739803851e3999","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:19:34 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:19:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 22:19:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00600417440643762714085e3999","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:19:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:19:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 22:19:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00600417440643795584438e3999","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:19:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:19:43 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 22:19:43 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 22:22:22 - WARNING - pixivdrive.py - 127 - Failed to add salt to page tmp/128710200/128710200_p0.gif, upload original page.
2025-04-07 22:22:23 - WARNING - pixivdrive.py - 155 - Failed to make mirage for page tmp/128710200/128710200_p0.gif.
2025-04-07 22:22:50 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800317440645702787994e1df3","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:22:50 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:22:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 22:22:51 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800317440645715628202e1df3","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:22:51 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:22:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 22:22:54 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800317440645738488551e1df3","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:22:54 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:22:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 22:22:57 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800317440645771561041e1df3","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:22:57 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:23:01 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 22:23:01 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 22:23:28 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800317440646082845058e1df3","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:23:28 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:23:29 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 22:23:29 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800317440646095715206e1df3","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:23:29 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:23:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 22:23:32 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800317440646118915435e1df3","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:23:32 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:23:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 22:23:35 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800317440646151805796e1df3","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:23:35 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:23:39 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 22:23:39 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 22:28:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/12/28/01/05/56/125311976_p0.jpg
2025-04-07 22:32:18 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440651385726117e022e","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:32:18 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:32:19 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 22:32:20 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440651398886266e022e","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:32:20 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:32:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 22:32:22 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440651422056595e022e","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:32:22 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:32:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 22:32:25 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440651455207079e022e","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:32:25 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:32:29 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 22:32:29 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 22:38:53 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801217440655331885401e1dba","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:38:53 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:38:54 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 22:38:54 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801217440655344715521e1dba","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:38:54 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:38:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 22:38:56 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801217440655367625759e1dba","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:38:56 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:38:59 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 22:39:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801217440655400466100e1dba","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:39:00 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:39:04 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 22:39:04 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 22:41:50 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440657104073200ee769","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:41:50 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:41:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 22:41:51 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440657116933337ee769","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:41:51 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:41:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 22:41:54 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440657140043593ee769","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:41:54 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:41:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 22:41:57 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440657173194067ee769","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:41:57 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:42:01 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 22:42:01 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 22:42:28 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/12/08/01/44/06/124990912_p0.png
2025-04-07 22:48:54 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2025/02/09/00/08/24/127038502_p0.jpg
2025-04-07 22:56:07 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801717440665676426624e0269","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:56:07 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:56:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 22:56:09 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801717440665689266852e0269","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:56:09 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:56:11 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 22:56:11 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801717440665712207097e0269","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:56:11 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:56:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 22:56:14 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801717440665745257543e0269","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:56:14 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:56:18 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 22:56:18 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 22:58:09 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440666893612162e0231","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:58:09 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:58:10 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 22:58:10 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440666906752365e0231","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:58:10 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:58:12 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 22:58:13 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440666929872607e0231","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:58:13 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:58:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 22:58:16 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440666963063046e0231","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 22:58:16 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 22:58:20 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 22:58:20 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 23:04:08 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440670485213239e022c","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:04:08 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:04:09 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 23:04:09 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440670498053368e022c","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:04:09 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:04:11 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 23:04:12 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440670520923611e022c","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:04:12 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:04:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 23:04:15 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fc17440670553783922e022c","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:04:15 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:04:19 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 23:04:19 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 23:07:19 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0f817440672388808841e29bc","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:07:19 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:07:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 23:07:20 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0f817440672401871057e29bc","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:07:20 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:07:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 23:07:22 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0f817440672424721384e29bc","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:07:22 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:07:25 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 23:07:25 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0f817440672457622003e29bc","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:07:25 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:07:29 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 23:07:29 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 23:08:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2023/12/04/00/01/12/113933034_p0.jpg
2025-04-07 23:09:44 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00600617440673839097644e0942","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:09:44 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:09:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 23:09:45 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00600617440673852237786e0942","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:09:45 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:09:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 23:09:47 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00600617440673875408032e0942","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:09:47 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:09:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 23:09:51 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00600617440673908618442e0942","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:09:51 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:09:55 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 23:09:55 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 23:22:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00600417440681546533209e3996","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:22:34 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:22:35 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 23:22:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00600417440681559363383e3996","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:22:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:22:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 23:22:38 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00600417440681582223753e3996","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:22:38 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:22:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 23:22:41 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00600417440681615084099e3996","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:22:41 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:22:45 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 23:22:45 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 23:32:49 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800217440687691113399e0dbf","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:32:49 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:32:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 23:32:50 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800217440687704243599e0dbf","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:32:50 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:32:52 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 23:32:52 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800217440687727373838e0dbf","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:32:52 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:32:55 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 23:32:56 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800217440687760504295e0dbf","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:32:56 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:33:00 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 23:33:00 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 23:35:36 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701617440689359158223e2883","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:35:36 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:35:37 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 23:35:37 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701617440689372038315e2883","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:35:37 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:35:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 23:35:39 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701617440689394978567e2883","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:35:39 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:35:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 23:35:42 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00701617440689427848896e2883","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:35:42 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:35:46 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 23:35:46 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-07 23:50:48 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2024/11/24/19/59/33/124597570_p0.jpg
2025-04-07 23:53:10 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801717440699903201993e026c","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:53:10 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:53:11 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-07 23:53:11 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801717440699916052116e026c","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:53:11 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:53:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-07 23:53:14 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801717440699938912343e026c","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:53:14 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:53:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-07 23:53:17 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801717440699971732732e026c","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-07 23:53:17 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-07 23:53:21 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-07 23:53:21 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-08 00:01:05 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800317440704650364778e1dfe","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:01:05 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:01:06 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-08 00:01:06 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800317440704663194903e1dfe","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:01:06 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:01:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-08 00:01:08 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800317440704686015124e1dfe","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:01:08 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:01:11 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-08 00:01:12 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800317440704719075510e1dfe","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:01:12 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:01:16 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-08 00:01:16 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-08 00:06:26 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060df17440707858785324e023a","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:06:26 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:06:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-08 00:06:27 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060df17440707871955479e023a","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:06:27 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:06:29 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-08 00:06:29 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060df17440707895135715e023a","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:06:29 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:06:32 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-08 00:06:32 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060df17440707928276035e023a","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:06:32 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:06:36 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-08 00:06:36 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-08 00:11:17 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060df17440710774793384e022e","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:11:17 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:11:18 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-08 00:11:18 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060df17440710787973611e022e","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:11:18 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:11:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-08 00:11:21 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060df17440710811173995e022e","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:11:21 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:11:24 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-08 00:11:24 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0060df17440710844384627e022e","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:11:24 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:11:28 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-08 00:11:28 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-08 00:11:48 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00317440711078974739e0236","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:11:48 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:11:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-08 00:11:49 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00317440711091894972e0236","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:11:49 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:11:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-08 00:11:51 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00317440711114755304e0236","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:11:51 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:11:54 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-08 00:11:54 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a00317440711147595781e0236","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:11:54 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:11:58 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-08 00:11:58 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-08 00:13:45 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2025-04-08 00:14:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2025/02/09/18/22/12/127062628_p0.jpg
2025-04-08 00:23:06 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fa17440717864807229e305d","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:23:06 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:23:07 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-08 00:23:07 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fa17440717877647378e305d","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:23:07 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:23:09 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-08 00:23:10 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fa17440717900737704e305d","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:23:10 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:23:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-08 00:23:13 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fa17440717933608118e305d","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:23:13 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:23:17 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-08 00:23:17 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-08 00:24:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0f817440718864822872e29be","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:24:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:24:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-08 00:24:47 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0f817440718878063206e29be","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:24:47 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:24:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-08 00:24:50 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0f817440718901213688e29be","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:24:50 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:24:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-08 00:24:53 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0f817440718934354352e29be","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:24:53 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:24:57 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-08 00:24:57 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-08 00:26:23 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440719836945165ee76b","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:26:23 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:26:24 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-08 00:26:25 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440719849855309ee76b","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:26:25 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:26:27 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-08 00:26:27 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440719872735603ee76b","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:26:27 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:26:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-08 00:26:30 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440719905606036ee76b","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:26:30 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:26:34 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-08 00:26:34 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-08 00:27:50 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440720706941756ee76b","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:27:50 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:27:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-08 00:27:52 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440720719791893ee76b","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:27:52 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:27:54 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-08 00:27:54 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440720742642148ee76b","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:27:54 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:27:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-08 00:27:57 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440720775592571ee76b","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:27:57 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:28:01 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-08 00:28:01 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-08 00:28:13 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440720933404820ee76b","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:28:13 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:28:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-08 00:28:14 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00a0fb17440720946235009ee76b","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:28:14 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:28:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-08 00:28:17 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801717440720975076147e0263","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:28:17 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:28:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-08 00:28:20 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00801717440721008246585e0263","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:28:20 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:28:24 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-08 00:28:24 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-08 00:30:13 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800217440722135735202e0dbf","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:30:13 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:30:14 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-08 00:30:15 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800217440722148625391e0dbf","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:30:15 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:30:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-04-08 00:30:17 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800217440722171485794e0dbf","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:30:17 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:30:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-04-08 00:30:20 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800217440722204606248e0dbf","resultCode":"FileNameDisable","display_message":"ËØ∑‰øÆÊîπÂêçÁß∞Ôºå‰∏çËÉΩÂåÖÂê´Â≠óÁ¨¶ /*?:<>\"|\\"}
2025-04-08 00:30:20 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2025-04-08 00:30:24 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-04-08 00:30:24 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/59688623/Ame„ÇÇ„Å°·µïÃà*üç≠ - 59688623.
2025-04-08 00:35:53 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /9AQFjuzT%2F889478%2F66ab6608e3b9c49e356a4be0b2fa71712e82d699%2F67f46f377722248c4fde4cdfb0d133b0d831ee61?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5TXc4%2F62KVZjomjUhHL1WUBfPhanvbKmjz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNXG%2BVS3eq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneg3hewQxP7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSieq17s%2FXtuMkagAF3Ps7gbuhxCdymZXpK%2Fp9N2Dqgcg7F1bcK%2BUVSbTJYfWmGI%2FTz6ayfw%2B4ssoSjtgMs%2BTVOz7cSshzCQkd5R5L6ilHcm024kQ1AB7VDwwp9ZIOEqEK%2BC7%2BqOQBlrQlDZs40hEOTatoo8jSoarrygrLUgaVTeCJuTaOUqYyPt%2F14VSAA&uploadId=170E685B72314FB58B2CECEB75E6BD36&x-oss-access-key-id=STS.NWb85N5zx9KHP7z1eTpwvq3ax&x-oss-expires=1744076103&x-oss-signature=BZH4ELmgBVmS0Fz9M%2BnPErKNFvWAZgRTJyAOKXCd%2FwI%3D&x-oss-signature-version=OSS2
2025-04-08 00:39:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-04-08 00:39:30 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-04-08 00:40:01 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-04-08 00:40:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
