2024-08-23 12:23:19 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00804517244157992538389ed211","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:23:19 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:23:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-23 12:23:22 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00804517244158025208753ed211","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:23:22 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:23:26 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-23 12:23:26 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2024-08-23 12:28:28 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /QOA7NlfR%2F889478%2F6685379767043d4423c0406286920ffb5ca4427a%2F66c8804e7b911d9159164e069f1f62156ef68046?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DNBsDNpudb57ioUkPJvFobTfZhl7Xf1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNQqBW0%2Bnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneY5VN0QO8i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iftbyCPXtuMkagAERjL0fRc5kSGCUb6vQagjV56KN6MpB0b%2B1QEHnh4wb8vlU9gpplp5oWboIp437fVCoFng7zDPvnHZIjyEE8rvapcq%2BOw%2FmWhBb7GBf6n4cmbKXqPiFGXfall1tNOapmndqcTfJK1sSzNvTn7XVJ9aMdBGCQaY6pr7zmqBBqgg1lyAA&uploadId=996ECF5A8D864CEDB945CEC7AB18ACB6&x-oss-access-key-id=STS.NSxMzyK8zPzCPexXZNAyMxpt5&x-oss-expires=1724419678&x-oss-signature=4BiY3K4r10qcuzd6ASkgPz2%2BCn8O6yRX27qHABOwAdo%3D&x-oss-signature-version=OSS2
2024-08-23 12:29:00 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /QOA7NlfR%2F889478%2F6685379767043d4423c0406286920ffb5ca4427a%2F66c8804e7b911d9159164e069f1f62156ef68046?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DNBsDNpudb57ioUkPJvFobTfZhl7Xf1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNQqBW0%2Bnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneY5VN0QO8i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iftbyCPXtuMkagAERjL0fRc5kSGCUb6vQagjV56KN6MpB0b%2B1QEHnh4wb8vlU9gpplp5oWboIp437fVCoFng7zDPvnHZIjyEE8rvapcq%2BOw%2FmWhBb7GBf6n4cmbKXqPiFGXfall1tNOapmndqcTfJK1sSzNvTn7XVJ9aMdBGCQaY6pr7zmqBBqgg1lyAA&uploadId=996ECF5A8D864CEDB945CEC7AB18ACB6&x-oss-access-key-id=STS.NSxMzyK8zPzCPexXZNAyMxpt5&x-oss-expires=1724419678&x-oss-signature=4BiY3K4r10qcuzd6ASkgPz2%2BCn8O6yRX27qHABOwAdo%3D&x-oss-signature-version=OSS2
2024-08-23 12:30:37 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803817244162372276373ed934","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:30:37 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:30:38 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-23 12:30:38 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803817244162384856522ed934","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:30:38 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:30:40 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-23 12:30:40 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803817244162407426750ed934","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:30:40 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:30:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-23 12:30:44 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803817244162440017168ed934","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:30:44 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:30:48 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-23 12:30:48 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2024-08-23 12:30:58 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803817244162580988821ed934","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:30:58 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:30:59 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-23 12:30:59 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803817244162593688990ed934","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:30:59 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:31:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-23 12:31:01 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803817244162616451266ed934","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:31:01 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:31:04 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-23 12:31:05 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00803817244162649031695ed934","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:31:05 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:31:09 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-23 12:31:09 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2024-08-23 12:33:32 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /n3ke0yYp%2F889478%2F66a0ddc039398f6536d64ac19c22d47862b56b15%2F66c8817dd146635f16734403b24254f8321c76c9?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DNBsDNpudb57ioUkPJvFobTfZhl7Xf1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNQqBW0%2Bnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneY5VN0QO8i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iftbyCPXtuMkagAERjL0fRc5kSGCUb6vQagjV56KN6MpB0b%2B1QEHnh4wb8vlU9gpplp5oWboIp437fVCoFng7zDPvnHZIjyEE8rvapcq%2BOw%2FmWhBb7GBf6n4cmbKXqPiFGXfall1tNOapmndqcTfJK1sSzNvTn7XVJ9aMdBGCQaY6pr7zmqBBqgg1lyAA&uploadId=CFF8CC5569914F4288437C660A26A708&x-oss-access-key-id=STS.NSxMzyK8zPzCPexXZNAyMxpt5&x-oss-expires=1724419981&x-oss-signature=iLT20wIr5iIQrA04htmPvuwCuPAaGmZb8BPn6OmhJTY%3D&x-oss-signature-version=OSS2
2024-08-23 12:34:03 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /n3ke0yYp%2F889478%2F66a0ddc039398f6536d64ac19c22d47862b56b15%2F66c8817dd146635f16734403b24254f8321c76c9?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DNBsDNpudb57ioUkPJvFobTfZhl7Xf1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNQqBW0%2Bnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneY5VN0QO8i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iftbyCPXtuMkagAERjL0fRc5kSGCUb6vQagjV56KN6MpB0b%2B1QEHnh4wb8vlU9gpplp5oWboIp437fVCoFng7zDPvnHZIjyEE8rvapcq%2BOw%2FmWhBb7GBf6n4cmbKXqPiFGXfall1tNOapmndqcTfJK1sSzNvTn7XVJ9aMdBGCQaY6pr7zmqBBqgg1lyAA&uploadId=CFF8CC5569914F4288437C660A26A708&x-oss-access-key-id=STS.NSxMzyK8zPzCPexXZNAyMxpt5&x-oss-expires=1724419981&x-oss-signature=iLT20wIr5iIQrA04htmPvuwCuPAaGmZb8BPn6OmhJTY%3D&x-oss-signature-version=OSS2
2024-08-23 12:34:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /n3ke0yYp%2F889478%2F66a0ddc039398f6536d64ac19c22d47862b56b15%2F66c8817dd146635f16734403b24254f8321c76c9?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DNBsDNpudb57ioUkPJvFobTfZhl7Xf1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNQqBW0%2Bnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneY5VN0QO8i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iftbyCPXtuMkagAERjL0fRc5kSGCUb6vQagjV56KN6MpB0b%2B1QEHnh4wb8vlU9gpplp5oWboIp437fVCoFng7zDPvnHZIjyEE8rvapcq%2BOw%2FmWhBb7GBf6n4cmbKXqPiFGXfall1tNOapmndqcTfJK1sSzNvTn7XVJ9aMdBGCQaY6pr7zmqBBqgg1lyAA&uploadId=CFF8CC5569914F4288437C660A26A708&x-oss-access-key-id=STS.NSxMzyK8zPzCPexXZNAyMxpt5&x-oss-expires=1724419981&x-oss-signature=iLT20wIr5iIQrA04htmPvuwCuPAaGmZb8BPn6OmhJTY%3D&x-oss-signature-version=OSS2
2024-08-23 12:35:44 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Read timed out. (read timeout=30)")': /Y8dRz4GA%2F889478%2F6672db37c6715351df9c41ed9868969af2a24bdf%2F66c881efcc915078af74490596d56b55a56b7a10?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DNBsDNpudb57ioUkPJvFobTfZhl7Xf1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNQqBW0%2Bnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneY5VN0QO8i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iftbyCPXtuMkagAERjL0fRc5kSGCUb6vQagjV56KN6MpB0b%2B1QEHnh4wb8vlU9gpplp5oWboIp437fVCoFng7zDPvnHZIjyEE8rvapcq%2BOw%2FmWhBb7GBf6n4cmbKXqPiFGXfall1tNOapmndqcTfJK1sSzNvTn7XVJ9aMdBGCQaY6pr7zmqBBqgg1lyAA&uploadId=8511A8E93D044E0C90FFF47312651FE2&x-oss-access-key-id=STS.NSxMzyK8zPzCPexXZNAyMxpt5&x-oss-expires=1724420095&x-oss-signature=wNcyvgOCGa28EqjpUHRQ95v7pNzAvTh1pW7mqT%2BRhrA%3D&x-oss-signature-version=OSS2
2024-08-23 12:36:15 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /Y8dRz4GA%2F889478%2F6672db37c6715351df9c41ed9868969af2a24bdf%2F66c881efcc915078af74490596d56b55a56b7a10?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DNBsDNpudb57ioUkPJvFobTfZhl7Xf1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNQqBW0%2Bnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneY5VN0QO8i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iftbyCPXtuMkagAERjL0fRc5kSGCUb6vQagjV56KN6MpB0b%2B1QEHnh4wb8vlU9gpplp5oWboIp437fVCoFng7zDPvnHZIjyEE8rvapcq%2BOw%2FmWhBb7GBf6n4cmbKXqPiFGXfall1tNOapmndqcTfJK1sSzNvTn7XVJ9aMdBGCQaY6pr7zmqBBqgg1lyAA&uploadId=8511A8E93D044E0C90FFF47312651FE2&x-oss-access-key-id=STS.NSxMzyK8zPzCPexXZNAyMxpt5&x-oss-expires=1724420095&x-oss-signature=wNcyvgOCGa28EqjpUHRQ95v7pNzAvTh1pW7mqT%2BRhrA%3D&x-oss-signature-version=OSS2
2024-08-23 12:36:18 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/Y8dRz4GA%2F889478%2F6672db37c6715351df9c41ed9868969af2a24bdf%2F66c881efcc915078af74490596d56b55a56b7a10?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DNBsDNpudb57ioUkPJvFobTfZhl7Xf1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNQqBW0%2Bnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneY5VN0QO8i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iftbyCPXtuMkagAERjL0fRc5kSGCUb6vQagjV56KN6MpB0b%2B1QEHnh4wb8vlU9gpplp5oWboIp437fVCoFng7zDPvnHZIjyEE8rvapcq%2BOw%2FmWhBb7GBf6n4cmbKXqPiFGXfall1tNOapmndqcTfJK1sSzNvTn7XVJ9aMdBGCQaY6pr7zmqBBqgg1lyAA&uploadId=8511A8E93D044E0C90FFF47312651FE2&x-oss-access-key-id=STS.NSxMzyK8zPzCPexXZNAyMxpt5&x-oss-expires=1724420095&x-oss-signature=wNcyvgOCGa28EqjpUHRQ95v7pNzAvTh1pW7mqT%2BRhrA%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>66C88240D46E713131A4CBA7</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"988B73EE3F14457C6091A630317B4DCC"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-08-23 12:36:20 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/Y8dRz4GA%2F889478%2F6672db37c6715351df9c41ed9868969af2a24bdf%2F66c881efcc915078af74490596d56b55a56b7a10?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DNBsDNpudb57ioUkPJvFobTfZhl7Xf1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNQqBW0%2Bnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneY5VN0QO8i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iftbyCPXtuMkagAERjL0fRc5kSGCUb6vQagjV56KN6MpB0b%2B1QEHnh4wb8vlU9gpplp5oWboIp437fVCoFng7zDPvnHZIjyEE8rvapcq%2BOw%2FmWhBb7GBf6n4cmbKXqPiFGXfall1tNOapmndqcTfJK1sSzNvTn7XVJ9aMdBGCQaY6pr7zmqBBqgg1lyAA&uploadId=8511A8E93D044E0C90FFF47312651FE2&x-oss-access-key-id=STS.NSxMzyK8zPzCPexXZNAyMxpt5&x-oss-expires=1724420095&x-oss-signature=wNcyvgOCGa28EqjpUHRQ95v7pNzAvTh1pW7mqT%2BRhrA%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>66C88243D8670638366BDF5C</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"988B73EE3F14457C6091A630317B4DCC"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-08-23 12:36:21 - WARNING - base.py - 100 - https://cn-beijing-data.aliyundrive.net/Y8dRz4GA%2F889478%2F6672db37c6715351df9c41ed9868969af2a24bdf%2F66c881efcc915078af74490596d56b55a56b7a10?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DNBsDNpudb57ioUkPJvFobTfZhl7Xf1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNQqBW0%2Bnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneY5VN0QO8i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iftbyCPXtuMkagAERjL0fRc5kSGCUb6vQagjV56KN6MpB0b%2B1QEHnh4wb8vlU9gpplp5oWboIp437fVCoFng7zDPvnHZIjyEE8rvapcq%2BOw%2FmWhBb7GBf6n4cmbKXqPiFGXfall1tNOapmndqcTfJK1sSzNvTn7XVJ9aMdBGCQaY6pr7zmqBBqgg1lyAA&uploadId=8511A8E93D044E0C90FFF47312651FE2&x-oss-access-key-id=STS.NSxMzyK8zPzCPexXZNAyMxpt5&x-oss-expires=1724420095&x-oss-signature=wNcyvgOCGa28EqjpUHRQ95v7pNzAvTh1pW7mqT%2BRhrA%3D&x-oss-signature-version=OSS2:409:<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartAlreadyExist</Code>
  <Message>For sequential multipart upload, you can't overwrite uploaded parts.</Message>
  <RequestId>66C88244B8F877343078FFB1</RequestId>
  <HostId>cn-beijing-data.aliyundrive.net</HostId>
  <PartEtag>"988B73EE3F14457C6091A630317B4DCC"</PartEtag>
  <PartNumber>1</PartNumber>
  <EC>0042-00000108</EC>
  <RecommendDoc>https://api.aliyun.com/troubleshoot?q=0042-00000108</RecommendDoc>
</Error>

2024-08-23 12:36:21 - ERROR - aliyundrive.py - 1077 - File tmp/119782500/119782500_p0.png Part 1 upload failed.
2024-08-23 12:39:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817244167404267863e1405","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:39:00 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:39:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-23 12:39:01 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817244167416737967e1405","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:39:01 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:39:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-23 12:39:04 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817244167439388200e1405","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:39:04 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:39:07 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-23 12:39:07 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817244167471828586e1405","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:39:07 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:39:11 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-23 12:39:11 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2024-08-23 12:39:30 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817244167706193219e1405","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:39:30 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:39:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-23 12:39:32 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817244167718653468e1405","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:39:32 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:39:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-23 12:39:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817244167741163817e1405","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:39:34 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:39:37 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-23 12:39:37 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00700817244167773934187e1405","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:39:37 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:39:41 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-23 12:39:41 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
2024-08-23 12:44:24 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /KwM1TG8d%2F889478%2F63ad84602507d65f08d14e2c9a7aa3f83b9d4068%2F66c88409c9120c3427884574b0869a61c48b86d2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5DNBsDNpudb57ioUkPJvFobTfZhl7Xf1zz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNQqBW0%2Bnq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneY5VN0QO8i4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16iftbyCPXtuMkagAERjL0fRc5kSGCUb6vQagjV56KN6MpB0b%2B1QEHnh4wb8vlU9gpplp5oWboIp437fVCoFng7zDPvnHZIjyEE8rvapcq%2BOw%2FmWhBb7GBf6n4cmbKXqPiFGXfall1tNOapmndqcTfJK1sSzNvTn7XVJ9aMdBGCQaY6pr7zmqBBqgg1lyAA&uploadId=84BBF6567E9D4136BB7945D7771BA773&x-oss-access-key-id=STS.NSxMzyK8zPzCPexXZNAyMxpt5&x-oss-expires=1724420634&x-oss-signature=1h37hcUJAgo744AHYkFSULG%2FCeBTNj7o7WCFa4%2FWa94%3D&x-oss-signature-version=OSS2
2024-08-23 12:45:44 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00804517244171444013588ed21c","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:45:44 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:45:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2024-08-23 12:45:45 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00804517244171456483732ed21c","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:45:45 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:45:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2024-08-23 12:45:48 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00804517244171478923940ed21c","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:45:48 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:45:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2024-08-23 12:45:51 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00804517244171511394369ed21c","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|\\"}
2024-08-23 12:45:51 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2024-08-23 12:45:55 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2024-08-23 12:45:55 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/56627683/SWKL:D - 56627683.
