2023-10-15 12:46:16 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800d16973739763363659ec9a8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:46:16 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:46:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 12:46:17 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800d16973739775503868ec9a8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:46:17 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:46:19 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 12:46:19 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800d16973739797594227ec9a8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:46:19 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:46:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 12:46:23 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800d16973739830004746ec9a8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:46:23 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:46:27 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 12:46:27 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/45862765/SP³:p - 45862765.
2023-10-15 12:46:40 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800d16973740000987159ec9a8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:46:40 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:46:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 12:46:41 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800d16973740013077289ec9a8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:46:41 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:46:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 12:46:43 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800d16973740035497640ec9a8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:46:43 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:46:46 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 12:46:46 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800d16973740067658174ec9a8","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:46:46 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:46:50 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 12:46:50 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/45862765/SP³:p - 45862765.
2023-10-15 12:48:27 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800c16973741078706784eb071","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:48:27 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:48:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 12:48:29 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800c16973741090906966eb071","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:48:29 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:48:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 12:48:31 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800c16973741113007298eb071","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:48:31 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:48:34 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 12:48:34 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800c16973741145467703eb071","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:48:34 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:48:38 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 12:48:38 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/45862765/SP³:p - 45862765.
2023-10-15 12:53:50 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800716973744304476526e65c4","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:53:50 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:53:51 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 12:53:51 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800716973744316876678e65c4","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:53:51 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:53:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 12:53:54 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800716973744339006975e65c4","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:53:54 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:53:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 12:53:57 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800716973744371137432e65c4","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 12:53:57 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 12:54:01 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 12:54:01 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/45862765/SP³:p - 45862765.
2023-10-15 12:55:16 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 12:55:17 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 12:55:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 12:55:49 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 12:56:19 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 12:56:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 12:56:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 12:56:56 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 12:56:56 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/108965353/108965353_p12.jpg.
2023-10-15 12:57:27 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 12:57:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 12:57:58 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 12:58:00 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 12:58:30 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 12:58:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 12:59:03 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 12:59:07 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 12:59:07 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/108965353/108965353_p13.jpg.
2023-10-15 12:59:38 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 12:59:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:00:10 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:00:12 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:00:42 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:00:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:06:49 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800816973752098277709e5c1b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:06:49 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:06:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:06:51 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800816973752110447895e5c1b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:06:51 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:06:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:06:53 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800816973752132658145e5c1b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:06:53 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:06:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:06:56 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800816973752164898782e5c1b","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:06:56 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:07:00 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 13:07:00 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/45862765/SP³:p - 45862765.
2023-10-15 13:08:05 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:08:06 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:08:37 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:08:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:09:09 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:09:12 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:09:42 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:09:46 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 13:09:46 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/111749410/111749410.json.txt.
2023-10-15 13:10:17 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:10:18 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:10:48 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:10:50 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:12:00 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800716973755203162279e65c3","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:12:00 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:12:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:12:01 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800716973755215352458e65c3","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:12:01 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:12:03 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:12:03 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800716973755237502782e65c3","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:12:03 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:12:06 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:12:07 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800716973755269703296e65c3","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:12:07 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:12:11 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 13:12:11 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/45862765/SP³:p - 45862765.
2023-10-15 13:13:41 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fb16973756180635085ee80f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:13:41 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:13:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:13:43 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fb16973756229566021ee80f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:13:43 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:13:45 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:13:45 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fb16973756252196357ee80f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:13:45 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:13:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:13:48 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fb16973756284577003ee80f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:13:48 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:13:52 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 13:13:52 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/45862765/SP³:p - 45862765.
2023-10-15 13:14:12 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fb16973756519402715ee80f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:14:12 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:14:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:14:13 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fb16973756531762918ee80f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:14:13 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:14:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:14:15 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fb16973756554203328ee80f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:14:15 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:14:18 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:14:18 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a0080fb16973756586843836ee80f","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:14:18 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:14:22 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 13:14:22 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/45862765/SP³:p - 45862765.
2023-10-15 13:19:36 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:19:37 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:20:07 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:20:09 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:20:39 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:20:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:21:12 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:21:16 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 13:21:16 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/110692360/110692360_p18.jpg.
2023-10-15 13:21:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:21:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:22:18 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:22:20 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:22:50 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:22:53 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:23:23 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:23:27 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 13:23:27 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/44554758/vivoさん - 44554758.
2023-10-15 13:23:59 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:24:00 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:24:30 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:24:32 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:25:02 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:25:05 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:26:10 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:26:11 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:26:41 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:26:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:27:13 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:27:16 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:27:47 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:27:51 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 13:27:51 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/91937004/91937004_p0.jpg.
2023-10-15 13:28:21 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:28:22 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:28:52 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:28:54 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:32:42 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:32:43 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:33:13 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:33:15 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:33:45 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:33:48 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:34:19 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:34:23 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 13:34:23 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/109075995/109075995.json.txt.
2023-10-15 13:34:55 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:34:56 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:35:26 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:35:28 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:35:59 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:36:02 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:36:32 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:36:36 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 13:36:36 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/109075995/109075995_p0.jpg.
2023-10-15 13:37:06 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:37:07 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:37:37 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:37:39 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:38:10 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2023-10-15 13:38:13 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:39:51 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800116973771909697988e442d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:39:51 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:39:52 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2023-10-15 13:39:52 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800116973771922088156e442d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:39:52 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:39:54 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2023-10-15 13:39:54 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800116973771944428450e442d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:39:54 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:39:57 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2023-10-15 13:39:57 - WARNING - base.py - 100 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:{"code":"FileNameDisable","message":"file name disable","requestId":"0a00800116973771976758842e442d","resultCode":"FileNameDisable","display_message":"请修改名称，不能包含字符 /*?:<>\"|"}
2023-10-15 13:39:57 - ERROR - aliyundrive.py - 80 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:403:file name disable
2023-10-15 13:40:01 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2023-10-15 13:40:01 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/45862765/SP³:p - 45862765.
