2025-03-23 22:24:39 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f778a950>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /1ml7drxQ%2F889478%2F67dfe48a2d9c12f8d47347cba49041cbedeac128%2F67e0891578e46d90bd7a466abdfc09df6c0d1a48?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=6EFFEC51ECBC41B99036A1E1582FF6F6&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742772005&x-oss-signature=Kw8NDrHdd79uYer7etVuEN1w2Q%2FP00aHRPPxND52%2B8M%3D&x-oss-signature-version=OSS2
2025-03-23 22:29:56 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7760b10>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /kMsPqRLp%2F889478%2F67ccd47373dc32ce5e7e4edf93f5edba112baff0%2F67e08b46eba6e81546cc4a458bbba32b73bc96a2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=FECBF1E6AC3143B5957CCFCDFA5CDE5B&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742772566&x-oss-signature=D3lvOC2MvHL9waJjDowJmAYLnILo7K%2B2SK%2F2o8CJ4Kk%3D&x-oss-signature-version=OSS2
2025-03-23 22:30:26 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7506cd0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /kMsPqRLp%2F889478%2F67ccd47373dc32ce5e7e4edf93f5edba112baff0%2F67e08b46eba6e81546cc4a458bbba32b73bc96a2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=FECBF1E6AC3143B5957CCFCDFA5CDE5B&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742772566&x-oss-signature=D3lvOC2MvHL9waJjDowJmAYLnILo7K%2B2SK%2F2o8CJ4Kk%3D&x-oss-signature-version=OSS2
2025-03-23 22:30:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f775b250>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /kMsPqRLp%2F889478%2F67ccd47373dc32ce5e7e4edf93f5edba112baff0%2F67e08b46eba6e81546cc4a458bbba32b73bc96a2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=FECBF1E6AC3143B5957CCFCDFA5CDE5B&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742772566&x-oss-signature=D3lvOC2MvHL9waJjDowJmAYLnILo7K%2B2SK%2F2o8CJ4Kk%3D&x-oss-signature-version=OSS2
2025-03-23 22:31:27 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/kMsPqRLp%2F889478%2F67ccd47373dc32ce5e7e4edf93f5edba112baff0%2F67e08b46eba6e81546cc4a458bbba32b73bc96a2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=FECBF1E6AC3143B5957CCFCDFA5CDE5B&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742772566&x-oss-signature=D3lvOC2MvHL9waJjDowJmAYLnILo7K%2B2SK%2F2o8CJ4Kk%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /kMsPqRLp%2F889478%2F67ccd47373dc32ce5e7e4edf93f5edba112baff0%2F67e08b46eba6e81546cc4a458bbba32b73bc96a2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=FECBF1E6AC3143B5957CCFCDFA5CDE5B&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742772566&x-oss-signature=D3lvOC2MvHL9waJjDowJmAYLnILo7K%2B2SK%2F2o8CJ4Kk%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7504fd0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 22:31:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7525110>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /kMsPqRLp%2F889478%2F67ccd47373dc32ce5e7e4edf93f5edba112baff0%2F67e08b46eba6e81546cc4a458bbba32b73bc96a2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=FECBF1E6AC3143B5957CCFCDFA5CDE5B&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742772566&x-oss-signature=D3lvOC2MvHL9waJjDowJmAYLnILo7K%2B2SK%2F2o8CJ4Kk%3D&x-oss-signature-version=OSS2
2025-03-23 22:32:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f774ba10>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /kMsPqRLp%2F889478%2F67ccd47373dc32ce5e7e4edf93f5edba112baff0%2F67e08b46eba6e81546cc4a458bbba32b73bc96a2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=FECBF1E6AC3143B5957CCFCDFA5CDE5B&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742772566&x-oss-signature=D3lvOC2MvHL9waJjDowJmAYLnILo7K%2B2SK%2F2o8CJ4Kk%3D&x-oss-signature-version=OSS2
2025-03-23 22:32:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f750f8d0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /kMsPqRLp%2F889478%2F67ccd47373dc32ce5e7e4edf93f5edba112baff0%2F67e08b46eba6e81546cc4a458bbba32b73bc96a2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=FECBF1E6AC3143B5957CCFCDFA5CDE5B&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742772566&x-oss-signature=D3lvOC2MvHL9waJjDowJmAYLnILo7K%2B2SK%2F2o8CJ4Kk%3D&x-oss-signature-version=OSS2
2025-03-23 22:33:27 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/kMsPqRLp%2F889478%2F67ccd47373dc32ce5e7e4edf93f5edba112baff0%2F67e08b46eba6e81546cc4a458bbba32b73bc96a2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=FECBF1E6AC3143B5957CCFCDFA5CDE5B&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742772566&x-oss-signature=D3lvOC2MvHL9waJjDowJmAYLnILo7K%2B2SK%2F2o8CJ4Kk%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /kMsPqRLp%2F889478%2F67ccd47373dc32ce5e7e4edf93f5edba112baff0%2F67e08b46eba6e81546cc4a458bbba32b73bc96a2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=FECBF1E6AC3143B5957CCFCDFA5CDE5B&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742772566&x-oss-signature=D3lvOC2MvHL9waJjDowJmAYLnILo7K%2B2SK%2F2o8CJ4Kk%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f750ef10>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 22:33:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f750ced0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /kMsPqRLp%2F889478%2F67ccd47373dc32ce5e7e4edf93f5edba112baff0%2F67e08b46eba6e81546cc4a458bbba32b73bc96a2?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=FECBF1E6AC3143B5957CCFCDFA5CDE5B&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742772566&x-oss-signature=D3lvOC2MvHL9waJjDowJmAYLnILo7K%2B2SK%2F2o8CJ4Kk%3D&x-oss-signature-version=OSS2
2025-03-23 22:39:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f750c410>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /PWNYONWJ%2F889478%2F64f32f8cef67997d22374bcd8272bfb822293b0d%2F67e08d86fa9ec22b4b7b4c899f139ed87ba97545?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=710A8110943245B4B54099E7CEDBDE0E&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773142&x-oss-signature=OVwLi0fv%2F6os%2FFsXaOiq81sOX9k%2FaFYQMMJGV5oH%2BlE%3D&x-oss-signature-version=OSS2
2025-03-23 22:40:04 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f750ecd0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /PWNYONWJ%2F889478%2F64f32f8cef67997d22374bcd8272bfb822293b0d%2F67e08d86fa9ec22b4b7b4c899f139ed87ba97545?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=710A8110943245B4B54099E7CEDBDE0E&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773142&x-oss-signature=OVwLi0fv%2F6os%2FFsXaOiq81sOX9k%2FaFYQMMJGV5oH%2BlE%3D&x-oss-signature-version=OSS2
2025-03-23 22:40:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7535950>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /PWNYONWJ%2F889478%2F64f32f8cef67997d22374bcd8272bfb822293b0d%2F67e08d86fa9ec22b4b7b4c899f139ed87ba97545?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=710A8110943245B4B54099E7CEDBDE0E&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773142&x-oss-signature=OVwLi0fv%2F6os%2FFsXaOiq81sOX9k%2FaFYQMMJGV5oH%2BlE%3D&x-oss-signature-version=OSS2
2025-03-23 22:41:04 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/PWNYONWJ%2F889478%2F64f32f8cef67997d22374bcd8272bfb822293b0d%2F67e08d86fa9ec22b4b7b4c899f139ed87ba97545?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=710A8110943245B4B54099E7CEDBDE0E&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773142&x-oss-signature=OVwLi0fv%2F6os%2FFsXaOiq81sOX9k%2FaFYQMMJGV5oH%2BlE%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /PWNYONWJ%2F889478%2F64f32f8cef67997d22374bcd8272bfb822293b0d%2F67e08d86fa9ec22b4b7b4c899f139ed87ba97545?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=710A8110943245B4B54099E7CEDBDE0E&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773142&x-oss-signature=OVwLi0fv%2F6os%2FFsXaOiq81sOX9k%2FaFYQMMJGV5oH%2BlE%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7535510>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 22:41:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7525890>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /PWNYONWJ%2F889478%2F64f32f8cef67997d22374bcd8272bfb822293b0d%2F67e08d86fa9ec22b4b7b4c899f139ed87ba97545?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=710A8110943245B4B54099E7CEDBDE0E&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773142&x-oss-signature=OVwLi0fv%2F6os%2FFsXaOiq81sOX9k%2FaFYQMMJGV5oH%2BlE%3D&x-oss-signature-version=OSS2
2025-03-23 22:42:05 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f777f690>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /PWNYONWJ%2F889478%2F64f32f8cef67997d22374bcd8272bfb822293b0d%2F67e08d86fa9ec22b4b7b4c899f139ed87ba97545?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=710A8110943245B4B54099E7CEDBDE0E&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773142&x-oss-signature=OVwLi0fv%2F6os%2FFsXaOiq81sOX9k%2FaFYQMMJGV5oH%2BlE%3D&x-oss-signature-version=OSS2
2025-03-23 22:42:35 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7535f50>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /PWNYONWJ%2F889478%2F64f32f8cef67997d22374bcd8272bfb822293b0d%2F67e08d86fa9ec22b4b7b4c899f139ed87ba97545?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=710A8110943245B4B54099E7CEDBDE0E&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773142&x-oss-signature=OVwLi0fv%2F6os%2FFsXaOiq81sOX9k%2FaFYQMMJGV5oH%2BlE%3D&x-oss-signature-version=OSS2
2025-03-23 22:43:05 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/PWNYONWJ%2F889478%2F64f32f8cef67997d22374bcd8272bfb822293b0d%2F67e08d86fa9ec22b4b7b4c899f139ed87ba97545?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=710A8110943245B4B54099E7CEDBDE0E&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773142&x-oss-signature=OVwLi0fv%2F6os%2FFsXaOiq81sOX9k%2FaFYQMMJGV5oH%2BlE%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /PWNYONWJ%2F889478%2F64f32f8cef67997d22374bcd8272bfb822293b0d%2F67e08d86fa9ec22b4b7b4c899f139ed87ba97545?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=710A8110943245B4B54099E7CEDBDE0E&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773142&x-oss-signature=OVwLi0fv%2F6os%2FFsXaOiq81sOX9k%2FaFYQMMJGV5oH%2BlE%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7534150>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 22:43:35 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7537ed0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /PWNYONWJ%2F889478%2F64f32f8cef67997d22374bcd8272bfb822293b0d%2F67e08d86fa9ec22b4b7b4c899f139ed87ba97545?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=710A8110943245B4B54099E7CEDBDE0E&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773142&x-oss-signature=OVwLi0fv%2F6os%2FFsXaOiq81sOX9k%2FaFYQMMJGV5oH%2BlE%3D&x-oss-signature-version=OSS2
2025-03-23 22:48:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f76fccd0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /ETbfgyV9%2F889478%2F67092e289a8855e85b3b492dab69cb37c31bb73e%2F67e08fbaa054c116df4842d6a7dbfcea74ae9668?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=404645707CF3490C82DD680FB822E3A7&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773706&x-oss-signature=sQI%2FFZHcyFhyAc8%2F15PwKtz9F59dP04wMKKJ0qAOgY4%3D&x-oss-signature-version=OSS2
2025-03-23 22:49:27 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f030f986c50>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /ETbfgyV9%2F889478%2F67092e289a8855e85b3b492dab69cb37c31bb73e%2F67e08fbaa054c116df4842d6a7dbfcea74ae9668?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=404645707CF3490C82DD680FB822E3A7&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773706&x-oss-signature=sQI%2FFZHcyFhyAc8%2F15PwKtz9F59dP04wMKKJ0qAOgY4%3D&x-oss-signature-version=OSS2
2025-03-23 22:49:57 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7739710>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /ETbfgyV9%2F889478%2F67092e289a8855e85b3b492dab69cb37c31bb73e%2F67e08fbaa054c116df4842d6a7dbfcea74ae9668?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=404645707CF3490C82DD680FB822E3A7&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773706&x-oss-signature=sQI%2FFZHcyFhyAc8%2F15PwKtz9F59dP04wMKKJ0qAOgY4%3D&x-oss-signature-version=OSS2
2025-03-23 22:50:27 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/ETbfgyV9%2F889478%2F67092e289a8855e85b3b492dab69cb37c31bb73e%2F67e08fbaa054c116df4842d6a7dbfcea74ae9668?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=404645707CF3490C82DD680FB822E3A7&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773706&x-oss-signature=sQI%2FFZHcyFhyAc8%2F15PwKtz9F59dP04wMKKJ0qAOgY4%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /ETbfgyV9%2F889478%2F67092e289a8855e85b3b492dab69cb37c31bb73e%2F67e08fbaa054c116df4842d6a7dbfcea74ae9668?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=404645707CF3490C82DD680FB822E3A7&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773706&x-oss-signature=sQI%2FFZHcyFhyAc8%2F15PwKtz9F59dP04wMKKJ0qAOgY4%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f752cf50>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 22:50:58 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f752cb10>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /ETbfgyV9%2F889478%2F67092e289a8855e85b3b492dab69cb37c31bb73e%2F67e08fbaa054c116df4842d6a7dbfcea74ae9668?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=404645707CF3490C82DD680FB822E3A7&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773706&x-oss-signature=sQI%2FFZHcyFhyAc8%2F15PwKtz9F59dP04wMKKJ0qAOgY4%3D&x-oss-signature-version=OSS2
2025-03-23 22:51:28 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f752fa90>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /ETbfgyV9%2F889478%2F67092e289a8855e85b3b492dab69cb37c31bb73e%2F67e08fbaa054c116df4842d6a7dbfcea74ae9668?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=404645707CF3490C82DD680FB822E3A7&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773706&x-oss-signature=sQI%2FFZHcyFhyAc8%2F15PwKtz9F59dP04wMKKJ0qAOgY4%3D&x-oss-signature-version=OSS2
2025-03-23 22:51:58 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f750fad0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /ETbfgyV9%2F889478%2F67092e289a8855e85b3b492dab69cb37c31bb73e%2F67e08fbaa054c116df4842d6a7dbfcea74ae9668?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=404645707CF3490C82DD680FB822E3A7&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773706&x-oss-signature=sQI%2FFZHcyFhyAc8%2F15PwKtz9F59dP04wMKKJ0qAOgY4%3D&x-oss-signature-version=OSS2
2025-03-23 22:52:28 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/ETbfgyV9%2F889478%2F67092e289a8855e85b3b492dab69cb37c31bb73e%2F67e08fbaa054c116df4842d6a7dbfcea74ae9668?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=404645707CF3490C82DD680FB822E3A7&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773706&x-oss-signature=sQI%2FFZHcyFhyAc8%2F15PwKtz9F59dP04wMKKJ0qAOgY4%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /ETbfgyV9%2F889478%2F67092e289a8855e85b3b492dab69cb37c31bb73e%2F67e08fbaa054c116df4842d6a7dbfcea74ae9668?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=404645707CF3490C82DD680FB822E3A7&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773706&x-oss-signature=sQI%2FFZHcyFhyAc8%2F15PwKtz9F59dP04wMKKJ0qAOgY4%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7777690>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 22:52:58 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f750e4d0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /ETbfgyV9%2F889478%2F67092e289a8855e85b3b492dab69cb37c31bb73e%2F67e08fbaa054c116df4842d6a7dbfcea74ae9668?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=404645707CF3490C82DD680FB822E3A7&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742773706&x-oss-signature=sQI%2FFZHcyFhyAc8%2F15PwKtz9F59dP04wMKKJ0qAOgY4%3D&x-oss-signature-version=OSS2
2025-03-23 22:58:40 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7507110>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /R5QJlPwt%2F889478%2F67df5aa5b0c9d373a6bd4e6cb3f0dc44faf52e11%2F67e0920201c6db8f37234ef68dba62f5d123d2ae?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=10F463B559244CDF9F6849332417BF93&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742774290&x-oss-signature=mdXQ8sCfNiZkx%2F%2BdktiEYfLZbMTqzqh2vv1w1t3TC7o%3D&x-oss-signature-version=OSS2
2025-03-23 22:59:10 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f750c510>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /R5QJlPwt%2F889478%2F67df5aa5b0c9d373a6bd4e6cb3f0dc44faf52e11%2F67e0920201c6db8f37234ef68dba62f5d123d2ae?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=10F463B559244CDF9F6849332417BF93&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742774290&x-oss-signature=mdXQ8sCfNiZkx%2F%2BdktiEYfLZbMTqzqh2vv1w1t3TC7o%3D&x-oss-signature-version=OSS2
2025-03-23 22:59:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f750c390>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /R5QJlPwt%2F889478%2F67df5aa5b0c9d373a6bd4e6cb3f0dc44faf52e11%2F67e0920201c6db8f37234ef68dba62f5d123d2ae?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=10F463B559244CDF9F6849332417BF93&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742774290&x-oss-signature=mdXQ8sCfNiZkx%2F%2BdktiEYfLZbMTqzqh2vv1w1t3TC7o%3D&x-oss-signature-version=OSS2
2025-03-23 23:00:11 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/R5QJlPwt%2F889478%2F67df5aa5b0c9d373a6bd4e6cb3f0dc44faf52e11%2F67e0920201c6db8f37234ef68dba62f5d123d2ae?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=10F463B559244CDF9F6849332417BF93&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742774290&x-oss-signature=mdXQ8sCfNiZkx%2F%2BdktiEYfLZbMTqzqh2vv1w1t3TC7o%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /R5QJlPwt%2F889478%2F67df5aa5b0c9d373a6bd4e6cb3f0dc44faf52e11%2F67e0920201c6db8f37234ef68dba62f5d123d2ae?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=10F463B559244CDF9F6849332417BF93&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742774290&x-oss-signature=mdXQ8sCfNiZkx%2F%2BdktiEYfLZbMTqzqh2vv1w1t3TC7o%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f750e050>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 23:00:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f750d8d0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /R5QJlPwt%2F889478%2F67df5aa5b0c9d373a6bd4e6cb3f0dc44faf52e11%2F67e0920201c6db8f37234ef68dba62f5d123d2ae?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=10F463B559244CDF9F6849332417BF93&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742774290&x-oss-signature=mdXQ8sCfNiZkx%2F%2BdktiEYfLZbMTqzqh2vv1w1t3TC7o%3D&x-oss-signature-version=OSS2
2025-03-23 23:01:11 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f750cb50>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /R5QJlPwt%2F889478%2F67df5aa5b0c9d373a6bd4e6cb3f0dc44faf52e11%2F67e0920201c6db8f37234ef68dba62f5d123d2ae?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=10F463B559244CDF9F6849332417BF93&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742774290&x-oss-signature=mdXQ8sCfNiZkx%2F%2BdktiEYfLZbMTqzqh2vv1w1t3TC7o%3D&x-oss-signature-version=OSS2
2025-03-23 23:01:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7510990>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /R5QJlPwt%2F889478%2F67df5aa5b0c9d373a6bd4e6cb3f0dc44faf52e11%2F67e0920201c6db8f37234ef68dba62f5d123d2ae?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=10F463B559244CDF9F6849332417BF93&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742774290&x-oss-signature=mdXQ8sCfNiZkx%2F%2BdktiEYfLZbMTqzqh2vv1w1t3TC7o%3D&x-oss-signature-version=OSS2
2025-03-23 23:02:11 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/R5QJlPwt%2F889478%2F67df5aa5b0c9d373a6bd4e6cb3f0dc44faf52e11%2F67e0920201c6db8f37234ef68dba62f5d123d2ae?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=10F463B559244CDF9F6849332417BF93&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742774290&x-oss-signature=mdXQ8sCfNiZkx%2F%2BdktiEYfLZbMTqzqh2vv1w1t3TC7o%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /R5QJlPwt%2F889478%2F67df5aa5b0c9d373a6bd4e6cb3f0dc44faf52e11%2F67e0920201c6db8f37234ef68dba62f5d123d2ae?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=10F463B559244CDF9F6849332417BF93&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742774290&x-oss-signature=mdXQ8sCfNiZkx%2F%2BdktiEYfLZbMTqzqh2vv1w1t3TC7o%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f76fa050>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 23:02:41 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7527cd0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /R5QJlPwt%2F889478%2F67df5aa5b0c9d373a6bd4e6cb3f0dc44faf52e11%2F67e0920201c6db8f37234ef68dba62f5d123d2ae?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5uAc9ncv6pt5ffaZkXerEICPsFKl67q0Tz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNWreYBzjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYneA%2FUeTRnVi4IClLcc%2BmqdsRIvJzWstJ7Gf9LWqChvSgk4TxhhcNFKSTQrInFCB0%2BcRObJl16i34QmLvXtuMkagAFPQfgZKSXLHRQ73yep6F2wRpSrI2qrcE3yVB6iJC0%2B3Wok2crH2383Mv1CDgJ7iXHdK2AphpV8sXUK6BUon809XAA8Ih7Py4Zr9Qe4HY5uju8reaep0Xl2Jo1s%2F5dxeWkBImO37faelxA7i32GKilJAKA063D3WbLbqmkaS8LcQyAA&uploadId=10F463B559244CDF9F6849332417BF93&x-oss-access-key-id=STS.NX58chRuLR51dcoHBW2NfxkA3&x-oss-expires=1742774290&x-oss-signature=mdXQ8sCfNiZkx%2F%2BdktiEYfLZbMTqzqh2vv1w1t3TC7o%3D&x-oss-signature-version=OSS2
2025-03-23 23:37:08 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7cfae10>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /iQ7hSufa%2F889478%2F67a2f69b2e75264422164aec9fb186b1a4581552%2F67e09b053969741fe4a34e05b111f1cc131c687c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=7211643F6E094A46A80F7E86AA64BF61&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742776597&x-oss-signature=eAxzA6hDGdjX7yYNFJl6S1gty0YeLJYEPALI8L4DxD0%3D&x-oss-signature-version=OSS2
2025-03-23 23:37:38 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7776cd0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /iQ7hSufa%2F889478%2F67a2f69b2e75264422164aec9fb186b1a4581552%2F67e09b053969741fe4a34e05b111f1cc131c687c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=7211643F6E094A46A80F7E86AA64BF61&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742776597&x-oss-signature=eAxzA6hDGdjX7yYNFJl6S1gty0YeLJYEPALI8L4DxD0%3D&x-oss-signature-version=OSS2
2025-03-23 23:38:08 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f76f2a50>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /iQ7hSufa%2F889478%2F67a2f69b2e75264422164aec9fb186b1a4581552%2F67e09b053969741fe4a34e05b111f1cc131c687c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=7211643F6E094A46A80F7E86AA64BF61&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742776597&x-oss-signature=eAxzA6hDGdjX7yYNFJl6S1gty0YeLJYEPALI8L4DxD0%3D&x-oss-signature-version=OSS2
2025-03-23 23:38:38 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/iQ7hSufa%2F889478%2F67a2f69b2e75264422164aec9fb186b1a4581552%2F67e09b053969741fe4a34e05b111f1cc131c687c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=7211643F6E094A46A80F7E86AA64BF61&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742776597&x-oss-signature=eAxzA6hDGdjX7yYNFJl6S1gty0YeLJYEPALI8L4DxD0%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /iQ7hSufa%2F889478%2F67a2f69b2e75264422164aec9fb186b1a4581552%2F67e09b053969741fe4a34e05b111f1cc131c687c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=7211643F6E094A46A80F7E86AA64BF61&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742776597&x-oss-signature=eAxzA6hDGdjX7yYNFJl6S1gty0YeLJYEPALI8L4DxD0%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f76f0710>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 23:39:08 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7535710>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /iQ7hSufa%2F889478%2F67a2f69b2e75264422164aec9fb186b1a4581552%2F67e09b053969741fe4a34e05b111f1cc131c687c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=7211643F6E094A46A80F7E86AA64BF61&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742776597&x-oss-signature=eAxzA6hDGdjX7yYNFJl6S1gty0YeLJYEPALI8L4DxD0%3D&x-oss-signature-version=OSS2
2025-03-23 23:39:38 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f778be90>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /iQ7hSufa%2F889478%2F67a2f69b2e75264422164aec9fb186b1a4581552%2F67e09b053969741fe4a34e05b111f1cc131c687c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=7211643F6E094A46A80F7E86AA64BF61&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742776597&x-oss-signature=eAxzA6hDGdjX7yYNFJl6S1gty0YeLJYEPALI8L4DxD0%3D&x-oss-signature-version=OSS2
2025-03-23 23:40:08 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7788910>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /iQ7hSufa%2F889478%2F67a2f69b2e75264422164aec9fb186b1a4581552%2F67e09b053969741fe4a34e05b111f1cc131c687c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=7211643F6E094A46A80F7E86AA64BF61&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742776597&x-oss-signature=eAxzA6hDGdjX7yYNFJl6S1gty0YeLJYEPALI8L4DxD0%3D&x-oss-signature-version=OSS2
2025-03-23 23:40:38 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/iQ7hSufa%2F889478%2F67a2f69b2e75264422164aec9fb186b1a4581552%2F67e09b053969741fe4a34e05b111f1cc131c687c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=7211643F6E094A46A80F7E86AA64BF61&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742776597&x-oss-signature=eAxzA6hDGdjX7yYNFJl6S1gty0YeLJYEPALI8L4DxD0%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /iQ7hSufa%2F889478%2F67a2f69b2e75264422164aec9fb186b1a4581552%2F67e09b053969741fe4a34e05b111f1cc131c687c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=7211643F6E094A46A80F7E86AA64BF61&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742776597&x-oss-signature=eAxzA6hDGdjX7yYNFJl6S1gty0YeLJYEPALI8L4DxD0%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f76f2690>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 23:41:08 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f76f3c90>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /iQ7hSufa%2F889478%2F67a2f69b2e75264422164aec9fb186b1a4581552%2F67e09b053969741fe4a34e05b111f1cc131c687c?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=7211643F6E094A46A80F7E86AA64BF61&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742776597&x-oss-signature=eAxzA6hDGdjX7yYNFJl6S1gty0YeLJYEPALI8L4DxD0%3D&x-oss-signature-version=OSS2
2025-03-23 23:46:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f774b750>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /x4bspxk7%2F889478%2F6751d04bfd588a0a71564e60b81978573144c7e8%2F67e09d3b842b290afd374904a3779ad4ce1e3660?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=8D40BC46DFDD4AF6B6DB7F3DC6DD76A8&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777163&x-oss-signature=ntKeWK9rfzo%2FuZ2HZ1eVrUd4DS0one%2BEZDgvVYcDOUc%3D&x-oss-signature-version=OSS2
2025-03-23 23:47:03 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7524210>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /x4bspxk7%2F889478%2F6751d04bfd588a0a71564e60b81978573144c7e8%2F67e09d3b842b290afd374904a3779ad4ce1e3660?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=8D40BC46DFDD4AF6B6DB7F3DC6DD76A8&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777163&x-oss-signature=ntKeWK9rfzo%2FuZ2HZ1eVrUd4DS0one%2BEZDgvVYcDOUc%3D&x-oss-signature-version=OSS2
2025-03-23 23:47:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7781590>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /x4bspxk7%2F889478%2F6751d04bfd588a0a71564e60b81978573144c7e8%2F67e09d3b842b290afd374904a3779ad4ce1e3660?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=8D40BC46DFDD4AF6B6DB7F3DC6DD76A8&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777163&x-oss-signature=ntKeWK9rfzo%2FuZ2HZ1eVrUd4DS0one%2BEZDgvVYcDOUc%3D&x-oss-signature-version=OSS2
2025-03-23 23:48:03 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/x4bspxk7%2F889478%2F6751d04bfd588a0a71564e60b81978573144c7e8%2F67e09d3b842b290afd374904a3779ad4ce1e3660?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=8D40BC46DFDD4AF6B6DB7F3DC6DD76A8&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777163&x-oss-signature=ntKeWK9rfzo%2FuZ2HZ1eVrUd4DS0one%2BEZDgvVYcDOUc%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /x4bspxk7%2F889478%2F6751d04bfd588a0a71564e60b81978573144c7e8%2F67e09d3b842b290afd374904a3779ad4ce1e3660?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=8D40BC46DFDD4AF6B6DB7F3DC6DD76A8&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777163&x-oss-signature=ntKeWK9rfzo%2FuZ2HZ1eVrUd4DS0one%2BEZDgvVYcDOUc%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7777ad0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 23:48:33 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f751dc10>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /x4bspxk7%2F889478%2F6751d04bfd588a0a71564e60b81978573144c7e8%2F67e09d3b842b290afd374904a3779ad4ce1e3660?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=8D40BC46DFDD4AF6B6DB7F3DC6DD76A8&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777163&x-oss-signature=ntKeWK9rfzo%2FuZ2HZ1eVrUd4DS0one%2BEZDgvVYcDOUc%3D&x-oss-signature-version=OSS2
2025-03-23 23:49:04 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f751dbd0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /x4bspxk7%2F889478%2F6751d04bfd588a0a71564e60b81978573144c7e8%2F67e09d3b842b290afd374904a3779ad4ce1e3660?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=8D40BC46DFDD4AF6B6DB7F3DC6DD76A8&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777163&x-oss-signature=ntKeWK9rfzo%2FuZ2HZ1eVrUd4DS0one%2BEZDgvVYcDOUc%3D&x-oss-signature-version=OSS2
2025-03-23 23:49:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f751ec10>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /x4bspxk7%2F889478%2F6751d04bfd588a0a71564e60b81978573144c7e8%2F67e09d3b842b290afd374904a3779ad4ce1e3660?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=8D40BC46DFDD4AF6B6DB7F3DC6DD76A8&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777163&x-oss-signature=ntKeWK9rfzo%2FuZ2HZ1eVrUd4DS0one%2BEZDgvVYcDOUc%3D&x-oss-signature-version=OSS2
2025-03-23 23:50:04 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/x4bspxk7%2F889478%2F6751d04bfd588a0a71564e60b81978573144c7e8%2F67e09d3b842b290afd374904a3779ad4ce1e3660?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=8D40BC46DFDD4AF6B6DB7F3DC6DD76A8&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777163&x-oss-signature=ntKeWK9rfzo%2FuZ2HZ1eVrUd4DS0one%2BEZDgvVYcDOUc%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /x4bspxk7%2F889478%2F6751d04bfd588a0a71564e60b81978573144c7e8%2F67e09d3b842b290afd374904a3779ad4ce1e3660?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=8D40BC46DFDD4AF6B6DB7F3DC6DD76A8&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777163&x-oss-signature=ntKeWK9rfzo%2FuZ2HZ1eVrUd4DS0one%2BEZDgvVYcDOUc%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f751c390>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 23:50:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f751fbd0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /x4bspxk7%2F889478%2F6751d04bfd588a0a71564e60b81978573144c7e8%2F67e09d3b842b290afd374904a3779ad4ce1e3660?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=8D40BC46DFDD4AF6B6DB7F3DC6DD76A8&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777163&x-oss-signature=ntKeWK9rfzo%2FuZ2HZ1eVrUd4DS0one%2BEZDgvVYcDOUc%3D&x-oss-signature-version=OSS2
2025-03-23 23:56:29 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f751f150>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /C0UicS7y%2F889478%2F679b3053fac404fc6123427a859fa4708ed89a59%2F67e09f8fd6a888de8e4b41e59b704d9e8d6da437?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=60CBC94DC1874CA2A4DBA7B51F40B25F&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777759&x-oss-signature=0kVaHxv5mrYOtYGFuoiymZ5udq0SXTg9Fj%2BhWQ7V73U%3D&x-oss-signature-version=OSS2
2025-03-23 23:56:59 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f030f986c50>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /C0UicS7y%2F889478%2F679b3053fac404fc6123427a859fa4708ed89a59%2F67e09f8fd6a888de8e4b41e59b704d9e8d6da437?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=60CBC94DC1874CA2A4DBA7B51F40B25F&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777759&x-oss-signature=0kVaHxv5mrYOtYGFuoiymZ5udq0SXTg9Fj%2BhWQ7V73U%3D&x-oss-signature-version=OSS2
2025-03-23 23:57:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f755ecd0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /C0UicS7y%2F889478%2F679b3053fac404fc6123427a859fa4708ed89a59%2F67e09f8fd6a888de8e4b41e59b704d9e8d6da437?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=60CBC94DC1874CA2A4DBA7B51F40B25F&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777759&x-oss-signature=0kVaHxv5mrYOtYGFuoiymZ5udq0SXTg9Fj%2BhWQ7V73U%3D&x-oss-signature-version=OSS2
2025-03-23 23:58:00 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/C0UicS7y%2F889478%2F679b3053fac404fc6123427a859fa4708ed89a59%2F67e09f8fd6a888de8e4b41e59b704d9e8d6da437?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=60CBC94DC1874CA2A4DBA7B51F40B25F&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777759&x-oss-signature=0kVaHxv5mrYOtYGFuoiymZ5udq0SXTg9Fj%2BhWQ7V73U%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /C0UicS7y%2F889478%2F679b3053fac404fc6123427a859fa4708ed89a59%2F67e09f8fd6a888de8e4b41e59b704d9e8d6da437?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=60CBC94DC1874CA2A4DBA7B51F40B25F&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777759&x-oss-signature=0kVaHxv5mrYOtYGFuoiymZ5udq0SXTg9Fj%2BhWQ7V73U%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f755d590>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-23 23:58:30 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7514b50>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /C0UicS7y%2F889478%2F679b3053fac404fc6123427a859fa4708ed89a59%2F67e09f8fd6a888de8e4b41e59b704d9e8d6da437?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=60CBC94DC1874CA2A4DBA7B51F40B25F&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777759&x-oss-signature=0kVaHxv5mrYOtYGFuoiymZ5udq0SXTg9Fj%2BhWQ7V73U%3D&x-oss-signature-version=OSS2
2025-03-23 23:59:00 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7515810>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /C0UicS7y%2F889478%2F679b3053fac404fc6123427a859fa4708ed89a59%2F67e09f8fd6a888de8e4b41e59b704d9e8d6da437?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=60CBC94DC1874CA2A4DBA7B51F40B25F&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777759&x-oss-signature=0kVaHxv5mrYOtYGFuoiymZ5udq0SXTg9Fj%2BhWQ7V73U%3D&x-oss-signature-version=OSS2
2025-03-23 23:59:31 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7516f90>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /C0UicS7y%2F889478%2F679b3053fac404fc6123427a859fa4708ed89a59%2F67e09f8fd6a888de8e4b41e59b704d9e8d6da437?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=60CBC94DC1874CA2A4DBA7B51F40B25F&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742777759&x-oss-signature=0kVaHxv5mrYOtYGFuoiymZ5udq0SXTg9Fj%2BhWQ7V73U%3D&x-oss-signature-version=OSS2
2025-03-24 00:13:45 - WARNING - aliyundrive.py - 831 - Token is about to expire, try to auto refresh.
2025-03-24 00:24:06 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /img-original/img/2025/03/08/11/39/05/127979387_p0.png
2025-03-24 00:28:35 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 00:28:36 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-03-24 00:29:06 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 00:29:08 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-03-24 00:29:38 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 00:29:41 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-03-24 00:30:11 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 00:30:15 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-03-24 00:30:15 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/125514029_mirage/125514029_p1.png.
2025-03-24 00:30:46 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 00:30:47 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-03-24 00:31:17 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 00:31:19 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-03-24 00:42:29 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /Be0jvg44%2F889478%2F66fa84dd6b72240bc1a148d395efec6da8bb8ef7%2F67e0aa37d76e7fe757124f14b97b2068d0958889?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=092753B2B35A46FB8DD9EDB73BD581EA&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742780487&x-oss-signature=PjPyiWxIiyupof9rojD1qrmBOm%2FRYAiWZuUdLG%2Fpmsc%3D&x-oss-signature-version=OSS2
2025-03-24 00:42:59 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7776cd0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /Be0jvg44%2F889478%2F66fa84dd6b72240bc1a148d395efec6da8bb8ef7%2F67e0aa37d76e7fe757124f14b97b2068d0958889?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=092753B2B35A46FB8DD9EDB73BD581EA&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742780487&x-oss-signature=PjPyiWxIiyupof9rojD1qrmBOm%2FRYAiWZuUdLG%2Fpmsc%3D&x-oss-signature-version=OSS2
2025-03-24 00:43:29 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7520a90>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /Be0jvg44%2F889478%2F66fa84dd6b72240bc1a148d395efec6da8bb8ef7%2F67e0aa37d76e7fe757124f14b97b2068d0958889?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=092753B2B35A46FB8DD9EDB73BD581EA&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742780487&x-oss-signature=PjPyiWxIiyupof9rojD1qrmBOm%2FRYAiWZuUdLG%2Fpmsc%3D&x-oss-signature-version=OSS2
2025-03-24 00:43:59 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/Be0jvg44%2F889478%2F66fa84dd6b72240bc1a148d395efec6da8bb8ef7%2F67e0aa37d76e7fe757124f14b97b2068d0958889?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=092753B2B35A46FB8DD9EDB73BD581EA&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742780487&x-oss-signature=PjPyiWxIiyupof9rojD1qrmBOm%2FRYAiWZuUdLG%2Fpmsc%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /Be0jvg44%2F889478%2F66fa84dd6b72240bc1a148d395efec6da8bb8ef7%2F67e0aa37d76e7fe757124f14b97b2068d0958889?partNumber=2&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=092753B2B35A46FB8DD9EDB73BD581EA&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742780487&x-oss-signature=PjPyiWxIiyupof9rojD1qrmBOm%2FRYAiWZuUdLG%2Fpmsc%3D&x-oss-signature-version=OSS2 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f75216d0>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)'))
2025-03-24 00:51:51 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f751e850>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /SV7nelSa%2F889478%2F67733558d2600de4b9f243008af2648374434082%2F67e0ac89b90e55c039fc43c585bc9fdd4f200b9d?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=570146B63BC74769BBFF0045F2C202D8&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742781081&x-oss-signature=ak0OKSVYsD2McM0L%2BgkrpMGaEraynuXWPcxtjGteLWY%3D&x-oss-signature-version=OSS2
2025-03-24 00:57:00 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 00:57:01 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-03-24 00:57:31 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 00:57:33 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-03-24 00:58:04 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 00:58:07 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-03-24 00:58:37 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 00:58:41 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-03-24 00:58:41 - ERROR - aliyundrive.py - 1046 - Failed to get create info of file tmp/127300343/127300343_p1.jpg.
2025-03-24 00:59:11 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 00:59:12 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-03-24 00:59:42 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 00:59:44 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-03-24 01:00:20 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /uelvciUL%2F889478%2F67df45ed5b882d6e6d9a4167afb1861455f431aa%2F67e0ae8678518f0fbe4c4bbcb178e6ecc0555cf5?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=96FCA0CC78194C4D8616CF008D0F7178&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742781590&x-oss-signature=TfUUgEYecSQgXk6G5Y5yyGV2pIgMdlTISffduLHlkS4%3D&x-oss-signature-version=OSS2
2025-03-24 01:05:11 - ERROR - base.py - 94 - https://api.aliyundrive.com/v2/file/complete:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 01:05:12 - WARNING - base.py - 25 - Retry func _post_file_complete 1 time.
2025-03-24 01:08:34 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /9WbgJOae%2F889478%2F674270fe5d9a12b84da74892bf72c23a441fa7c1%2F67e0b074f844cbe3e67c44838963a7e11e0280a6?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=075D438BBD4C49428E93351753998EDB&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742782084&x-oss-signature=6yu9dvFIu4%2Bb6jSpphPtMChLTjss5TFnHR33XNYYlqA%3D&x-oss-signature-version=OSS2
2025-03-24 01:09:05 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /9WbgJOae%2F889478%2F674270fe5d9a12b84da74892bf72c23a441fa7c1%2F67e0b074f844cbe3e67c44838963a7e11e0280a6?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=075D438BBD4C49428E93351753998EDB&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742782084&x-oss-signature=6yu9dvFIu4%2Bb6jSpphPtMChLTjss5TFnHR33XNYYlqA%3D&x-oss-signature-version=OSS2
2025-03-24 01:09:35 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7512690>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /9WbgJOae%2F889478%2F674270fe5d9a12b84da74892bf72c23a441fa7c1%2F67e0b074f844cbe3e67c44838963a7e11e0280a6?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=075D438BBD4C49428E93351753998EDB&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742782084&x-oss-signature=6yu9dvFIu4%2Bb6jSpphPtMChLTjss5TFnHR33XNYYlqA%3D&x-oss-signature-version=OSS2
2025-03-24 01:10:05 - ERROR - base.py - 94 - https://cn-beijing-data.aliyundrive.net/9WbgJOae%2F889478%2F674270fe5d9a12b84da74892bf72c23a441fa7c1%2F67e0b074f844cbe3e67c44838963a7e11e0280a6?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=075D438BBD4C49428E93351753998EDB&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742782084&x-oss-signature=6yu9dvFIu4%2Bb6jSpphPtMChLTjss5TFnHR33XNYYlqA%3D&x-oss-signature-version=OSS2:HTTPSConnectionPool(host='cn-beijing-data.aliyundrive.net', port=443): Max retries exceeded with url: /9WbgJOae%2F889478%2F674270fe5d9a12b84da74892bf72c23a441fa7c1%2F67e0b074f844cbe3e67c44838963a7e11e0280a6?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=075D438BBD4C49428E93351753998EDB&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742782084&x-oss-signature=6yu9dvFIu4%2Bb6jSpphPtMChLTjss5TFnHR33XNYYlqA%3D&x-oss-signature-version=OSS2 (Caused by ProtocolError('Connection aborted.', TimeoutError('The write operation timed out')))
2025-03-24 01:10:36 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02f7712290>, 'Connection to cn-beijing-data.aliyundrive.net timed out. (connect timeout=30)')': /9WbgJOae%2F889478%2F674270fe5d9a12b84da74892bf72c23a441fa7c1%2F67e0b074f844cbe3e67c44838963a7e11e0280a6?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=075D438BBD4C49428E93351753998EDB&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742782084&x-oss-signature=6yu9dvFIu4%2Bb6jSpphPtMChLTjss5TFnHR33XNYYlqA%3D&x-oss-signature-version=OSS2
2025-03-24 01:22:57 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 01:22:58 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-03-24 01:23:29 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 01:23:31 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-03-24 01:24:02 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 01:24:05 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 3 time.
2025-03-24 01:24:35 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 01:24:39 - ERROR - base.py - 36 - All retries failed in func _post_file_create_with_folders.
2025-03-24 01:24:39 - ERROR - aliyundrive.py - 966 - Failed to create folder pixiv/9202534/nicorima - 9202534.
2025-03-24 01:25:09 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 01:25:10 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 1 time.
2025-03-24 01:25:40 - ERROR - base.py - 94 - https://api.aliyundrive.com/adrive/v2/file/createWithFolders:HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Read timed out. (read timeout=30)
2025-03-24 01:25:42 - WARNING - base.py - 25 - Retry func _post_file_create_with_folders 2 time.
2025-03-24 01:26:18 - WARNING - connectionpool.py - 751 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError('The write operation timed out'))': /tH2fRQrH%2F889478%2F67dfe89d936f845e82ce4eab9fc4fb33f0fa9a5d%2F67e0b49c4307ad5c65f349cb8399f848805474fd?partNumber=1&security-token=CAISvgJ1q6Ft5B2yfSjIr5vkJeyDuulXjrbYdFPDizQfZdYbiYLy1Dz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNRCiUxvjq1HPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhcRm5sw9%2Byfo34lVYne4%2FBb0SLz7uHwufJ7FxfIREfquk63pvSlHLcLPe0Kjzzleo2k1XRPVFF%2B535IaHXuToXDnvSiHU6lCfXtuMkagAELEKfS42yTBLNShTZeU8BmaAAp6IaerkwSxOXv5M%2FvZq70Csxfk1lm6k6%2BzvEO%2B43798HVTRZTvsVz0UWmMLTMjhZvs10GE3B3Se%2BZ1S6qKP%2BtVGF29v8TPvBQAsLKPiBFyJG0FSlcX2pxyVWV8Kqk3NsQZ7r%2Fmlr0BxcF3TR4mCAA&uploadId=A9F47EDCB1A0446F92C08B5544BD7CE7&x-oss-access-key-id=STS.NXQnV7W6v9t3vuro4JiY7fGY6&x-oss-expires=1742783148&x-oss-signature=Ar9lJsTKKKuXWVIrzvYYwURXFtWnq4Y6QonfDM4nV18%3D&x-oss-signature-version=OSS2
